// Code generated by Fern. DO NOT EDIT.

package collateraltrading

import (
	context "context"
	sdk "github.com/whitebit-exchange/go-sdk"
	core "github.com/whitebit-exchange/go-sdk/core"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	option "github.com/whitebit-exchange/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// The endpoint returns a current [collateral balance](/glossary#balance-collateral).
//
// <Note>
// The API does not cache the response.
// </Note>
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
//
// <Accordion title="Errors">
// ```json
//
//	{
//	  "code": 30,
//	  "message": "Validation failed",
//	  "errors": {
//	    "ticker": ["ticker is invalid."]
//	  }
//	}
//
// ```
// </Accordion>
func (c *Client) CollateralAccountBalance(
	ctx context.Context,
	request *sdk.CollateralAccountBalanceRequest,
	opts ...option.RequestOption,
) (map[string]float64, error) {
	response, err := c.WithRawResponse.CollateralAccountBalance(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves collateral account balance summary with detailed breakdown per asset.
//
// <Note>
// The API does not cache the response.
// </Note>
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
//
// <Accordion title="Errors">
// ```json
//
//	{
//	  "code": 30,
//	  "message": "Validation failed",
//	  "errors": {
//	    "ticker": ["ticker is invalid."]
//	  }
//	}
//
// ```
// </Accordion>
func (c *Client) CollateralAccountBalanceSummary(
	ctx context.Context,
	request *sdk.CollateralAccountBalanceSummaryRequest,
	opts ...option.RequestOption,
) ([]*sdk.CollateralAccountBalanceSummaryResponseItem, error) {
	response, err := c.WithRawResponse.CollateralAccountBalanceSummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint creates [limit order](/glossary#limit-order) using [collateral balance](/glossary#balance-collateral).
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
//
// <Note>
// For open long position use **buy**, for short **sell**. To close current position, place opposite order with current position amount.
// </Note>
//
// <Note>
//   - RPI orders are post-only by design and cannot be used with the IOC flag. The API returns error code `37` when both `rpi=true` and `ioc=true` are used.
//
// </Note>
//
// <Accordion title="Error Codes">
//   - `30` - default validation error code
//   - `31` - market validation failed
//   - `32` - amount validation failed
//   - `33` - price validation failed
//   - `36` - client_order_id validation failed
//   - `37` - `ioc=true` cannot be used with `postOnly=true` or `rpi=true`
//
// </Accordion>
func (c *Client) CreateCollateralLimitOrder(
	ctx context.Context,
	request *sdk.CreateCollateralLimitOrderRequest,
	opts ...option.RequestOption,
) (*sdk.CreateCollateralLimitOrderResponse, error) {
	response, err := c.WithRawResponse.CreateCollateralLimitOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint creates multiple collateral limit orders.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CreateCollateralBulkOrder(
	ctx context.Context,
	request *sdk.CreateCollateralBulkOrderRequest,
	opts ...option.RequestOption,
) ([]*sdk.CreateCollateralBulkOrderResponseItem, error) {
	response, err := c.WithRawResponse.CreateCollateralBulkOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint creates a collateral market order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CreateCollateralMarketOrder(
	ctx context.Context,
	request *sdk.CreateCollateralMarketOrderRequest,
	opts ...option.RequestOption,
) (*sdk.CreateCollateralMarketOrderResponse, error) {
	response, err := c.WithRawResponse.CreateCollateralMarketOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint creates a collateral stop-limit order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CreateCollateralStopLimitOrder(
	ctx context.Context,
	request *sdk.CreateCollateralStopLimitOrderRequest,
	opts ...option.RequestOption,
) (*sdk.CreateCollateralStopLimitOrderResponse, error) {
	response, err := c.WithRawResponse.CreateCollateralStopLimitOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint creates a collateral trigger market order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CreateCollateralTriggerMarketOrder(
	ctx context.Context,
	request *sdk.CreateCollateralTriggerMarketOrderRequest,
	opts ...option.RequestOption,
) (*sdk.CreateCollateralTriggerMarketOrderResponse, error) {
	response, err := c.WithRawResponse.CreateCollateralTriggerMarketOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves collateral account summary.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) CollateralAccountSummary(
	ctx context.Context,
	request *sdk.CollateralAccountSummaryRequest,
	opts ...option.RequestOption,
) (*sdk.CollateralAccountSummaryResponse, error) {
	response, err := c.WithRawResponse.CollateralAccountSummary(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves open positions.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) GetOpenPositions(
	ctx context.Context,
	request *sdk.GetOpenPositionsRequest,
	opts ...option.RequestOption,
) ([]*sdk.GetOpenPositionsResponseItem, error) {
	response, err := c.WithRawResponse.GetOpenPositions(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint closes a position.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) ClosePosition(
	ctx context.Context,
	request *sdk.ClosePositionRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.ClosePosition(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// The endpoint retrieves positions history.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) GetPositionsHistory(
	ctx context.Context,
	request *sdk.GetPositionsHistoryRequest,
	opts ...option.RequestOption,
) ([]*sdk.GetPositionsHistoryResponseItem, error) {
	response, err := c.WithRawResponse.GetPositionsHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves funding history.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) GetFundingHistory(
	ctx context.Context,
	request *sdk.GetFundingHistoryRequest,
	opts ...option.RequestOption,
) (*sdk.GetFundingHistoryResponse, error) {
	response, err := c.WithRawResponse.GetFundingHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint changes account leverage.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) ChangeCollateralAccountLeverage(
	ctx context.Context,
	request *sdk.ChangeCollateralAccountLeverageRequest,
	opts ...option.RequestOption,
) (*sdk.ChangeCollateralAccountLeverageResponse, error) {
	response, err := c.WithRawResponse.ChangeCollateralAccountLeverage(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves hedge mode status.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) GetCollateralHedgeMode(
	ctx context.Context,
	request *sdk.GetCollateralHedgeModeRequest,
	opts ...option.RequestOption,
) (*sdk.GetCollateralHedgeModeResponse, error) {
	response, err := c.WithRawResponse.GetCollateralHedgeMode(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint updates hedge mode.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) UpdateHedgeMode(
	ctx context.Context,
	request *sdk.UpdateHedgeModeRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.UpdateHedgeMode(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// The endpoint retrieves active conditional orders.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) GetConditionalOrders(
	ctx context.Context,
	request *sdk.GetConditionalOrdersRequest,
	opts ...option.RequestOption,
) (*sdk.GetConditionalOrdersResponse, error) {
	response, err := c.WithRawResponse.GetConditionalOrders(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves active OCO orders.
//
// <Warning>
// Rate limit: 12000 requests/10 sec.
// </Warning>
func (c *Client) GetOcoOrders(
	ctx context.Context,
	request *sdk.GetOcoOrdersRequest,
	opts ...option.RequestOption,
) ([]*sdk.GetOcoOrdersResponseItem, error) {
	response, err := c.WithRawResponse.GetOcoOrders(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint creates a collateral OCO order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CreateCollateralOcoOrder(
	ctx context.Context,
	request *sdk.CreateCollateralOcoOrderRequest,
	opts ...option.RequestOption,
) (*sdk.CreateCollateralOcoOrderResponse, error) {
	response, err := c.WithRawResponse.CreateCollateralOcoOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint cancels a conditional order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CancelConditionalOrder(
	ctx context.Context,
	request *sdk.CancelConditionalOrderRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CancelConditionalOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}

// The endpoint cancels an OCO order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CancelOcoOrder(
	ctx context.Context,
	request *sdk.CancelOcoOrderRequest,
	opts ...option.RequestOption,
) (*sdk.CancelOcoOrderResponse, error) {
	response, err := c.WithRawResponse.CancelOcoOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint cancels an OTO order.
//
// <Warning>
// Rate limit: 10000 requests/10 sec.
// </Warning>
func (c *Client) CancelOtoOrder(
	ctx context.Context,
	request *sdk.CancelOtoOrderRequest,
	opts ...option.RequestOption,
) error {
	_, err := c.WithRawResponse.CancelOtoOrder(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return err
	}
	return nil
}
