// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	big "math/big"
)

var (
	postOauth2TokenRequestFieldClientID     = big.NewInt(1 << 0)
	postOauth2TokenRequestFieldClientSecret = big.NewInt(1 << 1)
	postOauth2TokenRequestFieldCode         = big.NewInt(1 << 2)
)

type PostOauth2TokenRequest struct {
	// The application's client ID
	ClientID string `json:"client_id" url:"-"`
	// The application's client secret
	ClientSecret string `json:"client_secret" url:"-"`
	// The authorization code received from the authorization endpoint
	Code string `json:"code" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostOauth2TokenRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenRequest) SetClientID(clientID string) {
	p.ClientID = clientID
	p.require(postOauth2TokenRequestFieldClientID)
}

// SetClientSecret sets the ClientSecret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenRequest) SetClientSecret(clientSecret string) {
	p.ClientSecret = clientSecret
	p.require(postOauth2TokenRequestFieldClientSecret)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenRequest) SetCode(code string) {
	p.Code = code
	p.require(postOauth2TokenRequestFieldCode)
}

func (p *PostOauth2TokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostOauth2TokenRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostOauth2TokenRequest(body)
	return nil
}

func (p *PostOauth2TokenRequest) MarshalJSON() ([]byte, error) {
	type embed PostOauth2TokenRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getAuthLoginRequestFieldClientID = big.NewInt(1 << 0)
	getAuthLoginRequestFieldState    = big.NewInt(1 << 1)
)

type GetAuthLoginRequest struct {
	// The application's client ID
	ClientID string `json:"-" url:"clientId"`
	// A secure random string used to maintain state between the request and callback and prevent CSRF attacks (Recommended)
	State *string `json:"-" url:"state,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetAuthLoginRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAuthLoginRequest) SetClientID(clientID string) {
	g.ClientID = clientID
	g.require(getAuthLoginRequestFieldClientID)
}

// SetState sets the State field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetAuthLoginRequest) SetState(state *string) {
	g.State = state
	g.require(getAuthLoginRequestFieldState)
}

var (
	postOauth2RefreshTokenRequestFieldClientID     = big.NewInt(1 << 0)
	postOauth2RefreshTokenRequestFieldClientSecret = big.NewInt(1 << 1)
	postOauth2RefreshTokenRequestFieldToken        = big.NewInt(1 << 2)
)

type PostOauth2RefreshTokenRequest struct {
	// The application's client ID
	ClientID string `json:"client_id" url:"-"`
	// The application's client secret
	ClientSecret string `json:"client_secret" url:"-"`
	// The refresh token received from the token endpoint
	Token string `json:"token" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (p *PostOauth2RefreshTokenRequest) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetClientID sets the ClientID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenRequest) SetClientID(clientID string) {
	p.ClientID = clientID
	p.require(postOauth2RefreshTokenRequestFieldClientID)
}

// SetClientSecret sets the ClientSecret field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenRequest) SetClientSecret(clientSecret string) {
	p.ClientSecret = clientSecret
	p.require(postOauth2RefreshTokenRequestFieldClientSecret)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenRequest) SetToken(token string) {
	p.Token = token
	p.require(postOauth2RefreshTokenRequestFieldToken)
}

func (p *PostOauth2RefreshTokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler PostOauth2RefreshTokenRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*p = PostOauth2RefreshTokenRequest(body)
	return nil
}

func (p *PostOauth2RefreshTokenRequest) MarshalJSON() ([]byte, error) {
	type embed PostOauth2RefreshTokenRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	postOauth2RefreshTokenResponseFieldData = big.NewInt(1 << 0)
)

type PostOauth2RefreshTokenResponse struct {
	Data *PostOauth2RefreshTokenResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostOauth2RefreshTokenResponse) GetData() *PostOauth2RefreshTokenResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PostOauth2RefreshTokenResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostOauth2RefreshTokenResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenResponse) SetData(data *PostOauth2RefreshTokenResponseData) {
	p.Data = data
	p.require(postOauth2RefreshTokenResponseFieldData)
}

func (p *PostOauth2RefreshTokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostOauth2RefreshTokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostOauth2RefreshTokenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostOauth2RefreshTokenResponse) MarshalJSON() ([]byte, error) {
	type embed PostOauth2RefreshTokenResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostOauth2RefreshTokenResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	postOauth2RefreshTokenResponseDataFieldAccessToken  = big.NewInt(1 << 0)
	postOauth2RefreshTokenResponseDataFieldExpiresIn    = big.NewInt(1 << 1)
	postOauth2RefreshTokenResponseDataFieldRefreshToken = big.NewInt(1 << 2)
	postOauth2RefreshTokenResponseDataFieldScope        = big.NewInt(1 << 3)
	postOauth2RefreshTokenResponseDataFieldTokenType    = big.NewInt(1 << 4)
)

type PostOauth2RefreshTokenResponseData struct {
	// The new access token for API requests
	AccessToken *string `json:"access_token,omitempty" url:"access_token,omitempty"`
	// Token expiration time in seconds
	ExpiresIn *int `json:"expires_in,omitempty" url:"expires_in,omitempty"`
	// New refresh token
	RefreshToken *string `json:"refresh_token,omitempty" url:"refresh_token,omitempty"`
	// Comma-separated list of granted scopes
	Scope *string `json:"scope,omitempty" url:"scope,omitempty"`
	// Type of the token
	TokenType *string `json:"token_type,omitempty" url:"token_type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostOauth2RefreshTokenResponseData) GetAccessToken() *string {
	if p == nil {
		return nil
	}
	return p.AccessToken
}

func (p *PostOauth2RefreshTokenResponseData) GetExpiresIn() *int {
	if p == nil {
		return nil
	}
	return p.ExpiresIn
}

func (p *PostOauth2RefreshTokenResponseData) GetRefreshToken() *string {
	if p == nil {
		return nil
	}
	return p.RefreshToken
}

func (p *PostOauth2RefreshTokenResponseData) GetScope() *string {
	if p == nil {
		return nil
	}
	return p.Scope
}

func (p *PostOauth2RefreshTokenResponseData) GetTokenType() *string {
	if p == nil {
		return nil
	}
	return p.TokenType
}

func (p *PostOauth2RefreshTokenResponseData) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostOauth2RefreshTokenResponseData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAccessToken sets the AccessToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenResponseData) SetAccessToken(accessToken *string) {
	p.AccessToken = accessToken
	p.require(postOauth2RefreshTokenResponseDataFieldAccessToken)
}

// SetExpiresIn sets the ExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenResponseData) SetExpiresIn(expiresIn *int) {
	p.ExpiresIn = expiresIn
	p.require(postOauth2RefreshTokenResponseDataFieldExpiresIn)
}

// SetRefreshToken sets the RefreshToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenResponseData) SetRefreshToken(refreshToken *string) {
	p.RefreshToken = refreshToken
	p.require(postOauth2RefreshTokenResponseDataFieldRefreshToken)
}

// SetScope sets the Scope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenResponseData) SetScope(scope *string) {
	p.Scope = scope
	p.require(postOauth2RefreshTokenResponseDataFieldScope)
}

// SetTokenType sets the TokenType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2RefreshTokenResponseData) SetTokenType(tokenType *string) {
	p.TokenType = tokenType
	p.require(postOauth2RefreshTokenResponseDataFieldTokenType)
}

func (p *PostOauth2RefreshTokenResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PostOauth2RefreshTokenResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostOauth2RefreshTokenResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostOauth2RefreshTokenResponseData) MarshalJSON() ([]byte, error) {
	type embed PostOauth2RefreshTokenResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostOauth2RefreshTokenResponseData) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	postOauth2TokenResponseFieldData = big.NewInt(1 << 0)
)

type PostOauth2TokenResponse struct {
	Data *PostOauth2TokenResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostOauth2TokenResponse) GetData() *PostOauth2TokenResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PostOauth2TokenResponse) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostOauth2TokenResponse) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenResponse) SetData(data *PostOauth2TokenResponseData) {
	p.Data = data
	p.require(postOauth2TokenResponseFieldData)
}

func (p *PostOauth2TokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler PostOauth2TokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostOauth2TokenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostOauth2TokenResponse) MarshalJSON() ([]byte, error) {
	type embed PostOauth2TokenResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostOauth2TokenResponse) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}

var (
	postOauth2TokenResponseDataFieldAccessToken  = big.NewInt(1 << 0)
	postOauth2TokenResponseDataFieldExpiresIn    = big.NewInt(1 << 1)
	postOauth2TokenResponseDataFieldRefreshToken = big.NewInt(1 << 2)
	postOauth2TokenResponseDataFieldScope        = big.NewInt(1 << 3)
	postOauth2TokenResponseDataFieldTokenType    = big.NewInt(1 << 4)
)

type PostOauth2TokenResponseData struct {
	// The access token for API requests
	AccessToken *string `json:"access_token,omitempty" url:"access_token,omitempty"`
	// Token expiration time in seconds
	ExpiresIn *int `json:"expires_in,omitempty" url:"expires_in,omitempty"`
	// Token used to refresh the access token
	RefreshToken *string `json:"refresh_token,omitempty" url:"refresh_token,omitempty"`
	// Comma-separated list of granted scopes
	Scope *string `json:"scope,omitempty" url:"scope,omitempty"`
	// Type of the token
	TokenType *string `json:"token_type,omitempty" url:"token_type,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (p *PostOauth2TokenResponseData) GetAccessToken() *string {
	if p == nil {
		return nil
	}
	return p.AccessToken
}

func (p *PostOauth2TokenResponseData) GetExpiresIn() *int {
	if p == nil {
		return nil
	}
	return p.ExpiresIn
}

func (p *PostOauth2TokenResponseData) GetRefreshToken() *string {
	if p == nil {
		return nil
	}
	return p.RefreshToken
}

func (p *PostOauth2TokenResponseData) GetScope() *string {
	if p == nil {
		return nil
	}
	return p.Scope
}

func (p *PostOauth2TokenResponseData) GetTokenType() *string {
	if p == nil {
		return nil
	}
	return p.TokenType
}

func (p *PostOauth2TokenResponseData) GetExtraProperties() map[string]interface{} {
	return p.extraProperties
}

func (p *PostOauth2TokenResponseData) require(field *big.Int) {
	if p.explicitFields == nil {
		p.explicitFields = big.NewInt(0)
	}
	p.explicitFields.Or(p.explicitFields, field)
}

// SetAccessToken sets the AccessToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenResponseData) SetAccessToken(accessToken *string) {
	p.AccessToken = accessToken
	p.require(postOauth2TokenResponseDataFieldAccessToken)
}

// SetExpiresIn sets the ExpiresIn field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenResponseData) SetExpiresIn(expiresIn *int) {
	p.ExpiresIn = expiresIn
	p.require(postOauth2TokenResponseDataFieldExpiresIn)
}

// SetRefreshToken sets the RefreshToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenResponseData) SetRefreshToken(refreshToken *string) {
	p.RefreshToken = refreshToken
	p.require(postOauth2TokenResponseDataFieldRefreshToken)
}

// SetScope sets the Scope field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenResponseData) SetScope(scope *string) {
	p.Scope = scope
	p.require(postOauth2TokenResponseDataFieldScope)
}

// SetTokenType sets the TokenType field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (p *PostOauth2TokenResponseData) SetTokenType(tokenType *string) {
	p.TokenType = tokenType
	p.require(postOauth2TokenResponseDataFieldTokenType)
}

func (p *PostOauth2TokenResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler PostOauth2TokenResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*p = PostOauth2TokenResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *p)
	if err != nil {
		return err
	}
	p.extraProperties = extraProperties
	p.rawJSON = json.RawMessage(data)
	return nil
}

func (p *PostOauth2TokenResponseData) MarshalJSON() ([]byte, error) {
	type embed PostOauth2TokenResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*p),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, p.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (p *PostOauth2TokenResponseData) String() string {
	if len(p.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(p.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(p); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", p)
}
