// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	big "math/big"
)

var (
	applyCodeRequestFieldCode       = big.NewInt(1 << 0)
	applyCodeRequestFieldPassphrase = big.NewInt(1 << 1)
	applyCodeRequestFieldRequest    = big.NewInt(1 << 2)
	applyCodeRequestFieldNonce      = big.NewInt(1 << 3)
)

type ApplyCodeRequest struct {
	// [Code](/glossary#whitebit-codes) that will be applied.
	Code string `json:"code" url:"-"`
	// Should be provided if the [code](/glossary#whitebit-codes) was created with passphrase. Max: 25 symbols.
	Passphrase *string `json:"passphrase,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (a *ApplyCodeRequest) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeRequest) SetCode(code string) {
	a.Code = code
	a.require(applyCodeRequestFieldCode)
}

// SetPassphrase sets the Passphrase field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeRequest) SetPassphrase(passphrase *string) {
	a.Passphrase = passphrase
	a.require(applyCodeRequestFieldPassphrase)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeRequest) SetRequest(request string) {
	a.Request = request
	a.require(applyCodeRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeRequest) SetNonce(nonce string) {
	a.Nonce = nonce
	a.require(applyCodeRequestFieldNonce)
}

func (a *ApplyCodeRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler ApplyCodeRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*a = ApplyCodeRequest(body)
	return nil
}

func (a *ApplyCodeRequest) MarshalJSON() ([]byte, error) {
	type embed ApplyCodeRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	createCodeRequestFieldTicker      = big.NewInt(1 << 0)
	createCodeRequestFieldAmount      = big.NewInt(1 << 1)
	createCodeRequestFieldPassphrase  = big.NewInt(1 << 2)
	createCodeRequestFieldDescription = big.NewInt(1 << 3)
	createCodeRequestFieldRequest     = big.NewInt(1 << 4)
	createCodeRequestFieldNonce       = big.NewInt(1 << 5)
)

type CreateCodeRequest struct {
	// Currency's [ticker](/glossary#ticker). Example: BTC
	Ticker string `json:"ticker" url:"-"`
	// Amount to transfer. Max [precision](/glossary#precision) = 8, value must be greater than zero and less than or equal to the [main balance](/glossary#balance-main).
	Amount string `json:"amount" url:"-"`
	// Passphrase for applying [WhiteBIT codes](/glossary#whitebit-codes). Passphrase must contain only latin letters, numbers and symbols (like !@#$%^, no whitespaces). Max: 25 symbols.
	Passphrase *string `json:"passphrase,omitempty" url:"-"`
	// Additional text description for [code](/glossary#whitebit-codes). Visible only for creator. Max: 75 symbols.
	Description *string `json:"description,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateCodeRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeRequest) SetTicker(ticker string) {
	c.Ticker = ticker
	c.require(createCodeRequestFieldTicker)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeRequest) SetAmount(amount string) {
	c.Amount = amount
	c.require(createCodeRequestFieldAmount)
}

// SetPassphrase sets the Passphrase field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeRequest) SetPassphrase(passphrase *string) {
	c.Passphrase = passphrase
	c.require(createCodeRequestFieldPassphrase)
}

// SetDescription sets the Description field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeRequest) SetDescription(description *string) {
	c.Description = description
	c.require(createCodeRequestFieldDescription)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeRequest) SetRequest(request string) {
	c.Request = request
	c.require(createCodeRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeRequest) SetNonce(nonce string) {
	c.Nonce = nonce
	c.require(createCodeRequestFieldNonce)
}

func (c *CreateCodeRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCodeRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateCodeRequest(body)
	return nil
}

func (c *CreateCodeRequest) MarshalJSON() ([]byte, error) {
	type embed CreateCodeRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getCodesHistoryRequestFieldLimit   = big.NewInt(1 << 0)
	getCodesHistoryRequestFieldOffset  = big.NewInt(1 << 1)
	getCodesHistoryRequestFieldRequest = big.NewInt(1 << 2)
	getCodesHistoryRequestFieldNonce   = big.NewInt(1 << 3)
)

type GetCodesHistoryRequest struct {
	// LIMIT is a special clause used to limit records a particular query can return.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Use the OFFSET clause to return entries starting from a particular line.
	Offset *int `json:"offset,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetCodesHistoryRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getCodesHistoryRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryRequest) SetOffset(offset *int) {
	g.Offset = offset
	g.require(getCodesHistoryRequestFieldOffset)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryRequest) SetRequest(request string) {
	g.Request = request
	g.require(getCodesHistoryRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryRequest) SetNonce(nonce string) {
	g.Nonce = nonce
	g.require(getCodesHistoryRequestFieldNonce)
}

func (g *GetCodesHistoryRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCodesHistoryRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetCodesHistoryRequest(body)
	return nil
}

func (g *GetCodesHistoryRequest) MarshalJSON() ([]byte, error) {
	type embed GetCodesHistoryRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getMyCodesRequestFieldLimit   = big.NewInt(1 << 0)
	getMyCodesRequestFieldOffset  = big.NewInt(1 << 1)
	getMyCodesRequestFieldRequest = big.NewInt(1 << 2)
	getMyCodesRequestFieldNonce   = big.NewInt(1 << 3)
)

type GetMyCodesRequest struct {
	// LIMIT is a special clause used to limit records a particular query can return.
	Limit *int `json:"limit,omitempty" url:"-"`
	// Use the OFFSET clause to return entries starting from a particular line.
	Offset *int `json:"offset,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetMyCodesRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesRequest) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getMyCodesRequestFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesRequest) SetOffset(offset *int) {
	g.Offset = offset
	g.require(getMyCodesRequestFieldOffset)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesRequest) SetRequest(request string) {
	g.Request = request
	g.require(getMyCodesRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesRequest) SetNonce(nonce string) {
	g.Nonce = nonce
	g.require(getMyCodesRequestFieldNonce)
}

func (g *GetMyCodesRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMyCodesRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetMyCodesRequest(body)
	return nil
}

func (g *GetMyCodesRequest) MarshalJSON() ([]byte, error) {
	type embed GetMyCodesRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	codeHistoryFieldAmount     = big.NewInt(1 << 0)
	codeHistoryFieldCode       = big.NewInt(1 << 1)
	codeHistoryFieldDate       = big.NewInt(1 << 2)
	codeHistoryFieldStatus     = big.NewInt(1 << 3)
	codeHistoryFieldTicker     = big.NewInt(1 << 4)
	codeHistoryFieldExternalID = big.NewInt(1 << 5)
)

type CodeHistory struct {
	// Code amount change (- is created, + is applied)
	Amount *string `json:"amount,omitempty" url:"amount,omitempty"`
	// WhiteBIT code
	Code *string `json:"code,omitempty" url:"code,omitempty"`
	// Code activation timestamp (for applied) or code creation timestamp (for created)
	Date *int `json:"date,omitempty" url:"date,omitempty"`
	// Current code status
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Code [ticker](/glossary#ticker)
	Ticker *string `json:"ticker,omitempty" url:"ticker,omitempty"`
	// Code external identifier
	ExternalID *string `json:"external_id,omitempty" url:"external_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CodeHistory) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CodeHistory) GetCode() *string {
	if c == nil {
		return nil
	}
	return c.Code
}

func (c *CodeHistory) GetDate() *int {
	if c == nil {
		return nil
	}
	return c.Date
}

func (c *CodeHistory) GetStatus() *string {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CodeHistory) GetTicker() *string {
	if c == nil {
		return nil
	}
	return c.Ticker
}

func (c *CodeHistory) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CodeHistory) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CodeHistory) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeHistory) SetAmount(amount *string) {
	c.Amount = amount
	c.require(codeHistoryFieldAmount)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeHistory) SetCode(code *string) {
	c.Code = code
	c.require(codeHistoryFieldCode)
}

// SetDate sets the Date field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeHistory) SetDate(date *int) {
	c.Date = date
	c.require(codeHistoryFieldDate)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeHistory) SetStatus(status *string) {
	c.Status = status
	c.require(codeHistoryFieldStatus)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeHistory) SetTicker(ticker *string) {
	c.Ticker = ticker
	c.require(codeHistoryFieldTicker)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeHistory) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(codeHistoryFieldExternalID)
}

func (c *CodeHistory) UnmarshalJSON(data []byte) error {
	type unmarshaler CodeHistory
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CodeHistory(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CodeHistory) MarshalJSON() ([]byte, error) {
	type embed CodeHistory
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CodeHistory) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	codeInfoFieldAmount     = big.NewInt(1 << 0)
	codeInfoFieldCode       = big.NewInt(1 << 1)
	codeInfoFieldDate       = big.NewInt(1 << 2)
	codeInfoFieldStatus     = big.NewInt(1 << 3)
	codeInfoFieldTicker     = big.NewInt(1 << 4)
	codeInfoFieldExternalID = big.NewInt(1 << 5)
)

type CodeInfo struct {
	// Code amount
	Amount *string `json:"amount,omitempty" url:"amount,omitempty"`
	// WhiteBIT code
	Code *string `json:"code,omitempty" url:"code,omitempty"`
	// Code creation timestamp
	Date *int `json:"date,omitempty" url:"date,omitempty"`
	// Code status
	Status *string `json:"status,omitempty" url:"status,omitempty"`
	// Code [ticker](/glossary#ticker)
	Ticker *string `json:"ticker,omitempty" url:"ticker,omitempty"`
	// Code external identifier
	ExternalID *string `json:"external_id,omitempty" url:"external_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CodeInfo) GetAmount() *string {
	if c == nil {
		return nil
	}
	return c.Amount
}

func (c *CodeInfo) GetCode() *string {
	if c == nil {
		return nil
	}
	return c.Code
}

func (c *CodeInfo) GetDate() *int {
	if c == nil {
		return nil
	}
	return c.Date
}

func (c *CodeInfo) GetStatus() *string {
	if c == nil {
		return nil
	}
	return c.Status
}

func (c *CodeInfo) GetTicker() *string {
	if c == nil {
		return nil
	}
	return c.Ticker
}

func (c *CodeInfo) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CodeInfo) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CodeInfo) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeInfo) SetAmount(amount *string) {
	c.Amount = amount
	c.require(codeInfoFieldAmount)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeInfo) SetCode(code *string) {
	c.Code = code
	c.require(codeInfoFieldCode)
}

// SetDate sets the Date field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeInfo) SetDate(date *int) {
	c.Date = date
	c.require(codeInfoFieldDate)
}

// SetStatus sets the Status field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeInfo) SetStatus(status *string) {
	c.Status = status
	c.require(codeInfoFieldStatus)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeInfo) SetTicker(ticker *string) {
	c.Ticker = ticker
	c.require(codeInfoFieldTicker)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CodeInfo) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(codeInfoFieldExternalID)
}

func (c *CodeInfo) UnmarshalJSON(data []byte) error {
	type unmarshaler CodeInfo
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CodeInfo(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CodeInfo) MarshalJSON() ([]byte, error) {
	type embed CodeInfo
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CodeInfo) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	applyCodeResponseFieldMessage    = big.NewInt(1 << 0)
	applyCodeResponseFieldTicker     = big.NewInt(1 << 1)
	applyCodeResponseFieldAmount     = big.NewInt(1 << 2)
	applyCodeResponseFieldExternalID = big.NewInt(1 << 3)
)

type ApplyCodeResponse struct {
	Message    *string `json:"message,omitempty" url:"message,omitempty"`
	Ticker     *string `json:"ticker,omitempty" url:"ticker,omitempty"`
	Amount     *string `json:"amount,omitempty" url:"amount,omitempty"`
	ExternalID *string `json:"external_id,omitempty" url:"external_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (a *ApplyCodeResponse) GetMessage() *string {
	if a == nil {
		return nil
	}
	return a.Message
}

func (a *ApplyCodeResponse) GetTicker() *string {
	if a == nil {
		return nil
	}
	return a.Ticker
}

func (a *ApplyCodeResponse) GetAmount() *string {
	if a == nil {
		return nil
	}
	return a.Amount
}

func (a *ApplyCodeResponse) GetExternalID() *string {
	if a == nil {
		return nil
	}
	return a.ExternalID
}

func (a *ApplyCodeResponse) GetExtraProperties() map[string]interface{} {
	return a.extraProperties
}

func (a *ApplyCodeResponse) require(field *big.Int) {
	if a.explicitFields == nil {
		a.explicitFields = big.NewInt(0)
	}
	a.explicitFields.Or(a.explicitFields, field)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeResponse) SetMessage(message *string) {
	a.Message = message
	a.require(applyCodeResponseFieldMessage)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeResponse) SetTicker(ticker *string) {
	a.Ticker = ticker
	a.require(applyCodeResponseFieldTicker)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeResponse) SetAmount(amount *string) {
	a.Amount = amount
	a.require(applyCodeResponseFieldAmount)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (a *ApplyCodeResponse) SetExternalID(externalID *string) {
	a.ExternalID = externalID
	a.require(applyCodeResponseFieldExternalID)
}

func (a *ApplyCodeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler ApplyCodeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*a = ApplyCodeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *a)
	if err != nil {
		return err
	}
	a.extraProperties = extraProperties
	a.rawJSON = json.RawMessage(data)
	return nil
}

func (a *ApplyCodeResponse) MarshalJSON() ([]byte, error) {
	type embed ApplyCodeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*a),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, a.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (a *ApplyCodeResponse) String() string {
	if len(a.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(a.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(a); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", a)
}

var (
	createCodeResponseFieldCode       = big.NewInt(1 << 0)
	createCodeResponseFieldMessage    = big.NewInt(1 << 1)
	createCodeResponseFieldExternalID = big.NewInt(1 << 2)
)

type CreateCodeResponse struct {
	// Generated WhiteBIT code
	Code *string `json:"code,omitempty" url:"code,omitempty"`
	// Success message
	Message *string `json:"message,omitempty" url:"message,omitempty"`
	// External identifier
	ExternalID *string `json:"external_id,omitempty" url:"external_id,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateCodeResponse) GetCode() *string {
	if c == nil {
		return nil
	}
	return c.Code
}

func (c *CreateCodeResponse) GetMessage() *string {
	if c == nil {
		return nil
	}
	return c.Message
}

func (c *CreateCodeResponse) GetExternalID() *string {
	if c == nil {
		return nil
	}
	return c.ExternalID
}

func (c *CreateCodeResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateCodeResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetCode sets the Code field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeResponse) SetCode(code *string) {
	c.Code = code
	c.require(createCodeResponseFieldCode)
}

// SetMessage sets the Message field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeResponse) SetMessage(message *string) {
	c.Message = message
	c.require(createCodeResponseFieldMessage)
}

// SetExternalID sets the ExternalID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateCodeResponse) SetExternalID(externalID *string) {
	c.ExternalID = externalID
	c.require(createCodeResponseFieldExternalID)
}

func (c *CreateCodeResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateCodeResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateCodeResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateCodeResponse) MarshalJSON() ([]byte, error) {
	type embed CreateCodeResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateCodeResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getCodesHistoryResponseFieldTotal  = big.NewInt(1 << 0)
	getCodesHistoryResponseFieldData   = big.NewInt(1 << 1)
	getCodesHistoryResponseFieldLimit  = big.NewInt(1 << 2)
	getCodesHistoryResponseFieldOffset = big.NewInt(1 << 3)
)

type GetCodesHistoryResponse struct {
	// Total number of code history entries
	Total  *int           `json:"total,omitempty" url:"total,omitempty"`
	Data   []*CodeHistory `json:"data,omitempty" url:"data,omitempty"`
	Limit  *int           `json:"limit,omitempty" url:"limit,omitempty"`
	Offset *int           `json:"offset,omitempty" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetCodesHistoryResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GetCodesHistoryResponse) GetData() []*CodeHistory {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetCodesHistoryResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetCodesHistoryResponse) GetOffset() *int {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetCodesHistoryResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetCodesHistoryResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryResponse) SetTotal(total *int) {
	g.Total = total
	g.require(getCodesHistoryResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryResponse) SetData(data []*CodeHistory) {
	g.Data = data
	g.require(getCodesHistoryResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getCodesHistoryResponseFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetCodesHistoryResponse) SetOffset(offset *int) {
	g.Offset = offset
	g.require(getCodesHistoryResponseFieldOffset)
}

func (g *GetCodesHistoryResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetCodesHistoryResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetCodesHistoryResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetCodesHistoryResponse) MarshalJSON() ([]byte, error) {
	type embed GetCodesHistoryResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetCodesHistoryResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getMyCodesResponseFieldTotal  = big.NewInt(1 << 0)
	getMyCodesResponseFieldData   = big.NewInt(1 << 1)
	getMyCodesResponseFieldLimit  = big.NewInt(1 << 2)
	getMyCodesResponseFieldOffset = big.NewInt(1 << 3)
)

type GetMyCodesResponse struct {
	// Total number of codes
	Total  *int        `json:"total,omitempty" url:"total,omitempty"`
	Data   []*CodeInfo `json:"data,omitempty" url:"data,omitempty"`
	Limit  *int        `json:"limit,omitempty" url:"limit,omitempty"`
	Offset *int        `json:"offset,omitempty" url:"offset,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetMyCodesResponse) GetTotal() *int {
	if g == nil {
		return nil
	}
	return g.Total
}

func (g *GetMyCodesResponse) GetData() []*CodeInfo {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GetMyCodesResponse) GetLimit() *int {
	if g == nil {
		return nil
	}
	return g.Limit
}

func (g *GetMyCodesResponse) GetOffset() *int {
	if g == nil {
		return nil
	}
	return g.Offset
}

func (g *GetMyCodesResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetMyCodesResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTotal sets the Total field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesResponse) SetTotal(total *int) {
	g.Total = total
	g.require(getMyCodesResponseFieldTotal)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesResponse) SetData(data []*CodeInfo) {
	g.Data = data
	g.require(getMyCodesResponseFieldData)
}

// SetLimit sets the Limit field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesResponse) SetLimit(limit *int) {
	g.Limit = limit
	g.require(getMyCodesResponseFieldLimit)
}

// SetOffset sets the Offset field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetMyCodesResponse) SetOffset(offset *int) {
	g.Offset = offset
	g.require(getMyCodesResponseFieldOffset)
}

func (g *GetMyCodesResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetMyCodesResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetMyCodesResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetMyCodesResponse) MarshalJSON() ([]byte, error) {
	type embed GetMyCodesResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetMyCodesResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}
