// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	big "math/big"
	time "time"
)

var (
	createNewAddressRequestFieldTicker  = big.NewInt(1 << 0)
	createNewAddressRequestFieldNetwork = big.NewInt(1 << 1)
	createNewAddressRequestFieldType    = big.NewInt(1 << 2)
	createNewAddressRequestFieldRequest = big.NewInt(1 << 3)
	createNewAddressRequestFieldNonce   = big.NewInt(1 << 4)
)

type CreateNewAddressRequest struct {
	// Currency's ticker.
	Ticker string `json:"ticker" url:"-"`
	// Currency's network (for multinetwork currencies). Example: OMNI or TRC20 or ERC20. For USDT default network is ERC20(ETH).
	Network *string `json:"network,omitempty" url:"-"`
	// Address type, available for specific currencies list (see address types table in endpoint description)
	Type *CreateNewAddressRequestType `json:"type,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (c *CreateNewAddressRequest) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressRequest) SetTicker(ticker string) {
	c.Ticker = ticker
	c.require(createNewAddressRequestFieldTicker)
}

// SetNetwork sets the Network field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressRequest) SetNetwork(network *string) {
	c.Network = network
	c.require(createNewAddressRequestFieldNetwork)
}

// SetType sets the Type field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressRequest) SetType(type_ *CreateNewAddressRequestType) {
	c.Type = type_
	c.require(createNewAddressRequestFieldType)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressRequest) SetRequest(request string) {
	c.Request = request
	c.require(createNewAddressRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressRequest) SetNonce(nonce string) {
	c.Nonce = nonce
	c.require(createNewAddressRequestFieldNonce)
}

func (c *CreateNewAddressRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNewAddressRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*c = CreateNewAddressRequest(body)
	return nil
}

func (c *CreateNewAddressRequest) MarshalJSON() ([]byte, error) {
	type embed CreateNewAddressRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getDepositAddressRequestFieldTicker  = big.NewInt(1 << 0)
	getDepositAddressRequestFieldNetwork = big.NewInt(1 << 1)
	getDepositAddressRequestFieldRequest = big.NewInt(1 << 2)
	getDepositAddressRequestFieldNonce   = big.NewInt(1 << 3)
)

type GetDepositAddressRequest struct {
	// Currencies ticker. Example: BTC ⚠️ Currency [ticker](/glossary#ticker) should not be [fiat](/glossary#fiat) and it’s “can_deposit” status must be “true”. See [Asset Status endpoint](/public/http-v4/asset-status-list) response for the status.
	Ticker string `json:"ticker" url:"-"`
	// Cryptocurrency network. ⚠️ If currency has multiple networks like USDT, specify the network to use. See [ticker](/glossary#ticker) networks list in “networks” field from response [Asset Status endpoint](/public/http-v4/asset-status-list).
	Network *string `json:"network,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetDepositAddressRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressRequest) SetTicker(ticker string) {
	g.Ticker = ticker
	g.require(getDepositAddressRequestFieldTicker)
}

// SetNetwork sets the Network field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressRequest) SetNetwork(network *string) {
	g.Network = network
	g.require(getDepositAddressRequestFieldNetwork)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressRequest) SetRequest(request string) {
	g.Request = request
	g.require(getDepositAddressRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressRequest) SetNonce(nonce string) {
	g.Nonce = nonce
	g.require(getDepositAddressRequestFieldNonce)
}

func (g *GetDepositAddressRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDepositAddressRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetDepositAddressRequest(body)
	return nil
}

func (g *GetDepositAddressRequest) MarshalJSON() ([]byte, error) {
	type embed GetDepositAddressRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getFiatDepositURLRequestFieldTicker      = big.NewInt(1 << 0)
	getFiatDepositURLRequestFieldProvider    = big.NewInt(1 << 1)
	getFiatDepositURLRequestFieldAmount      = big.NewInt(1 << 2)
	getFiatDepositURLRequestFieldUniqueID    = big.NewInt(1 << 3)
	getFiatDepositURLRequestFieldCustomer    = big.NewInt(1 << 4)
	getFiatDepositURLRequestFieldSuccessLink = big.NewInt(1 << 5)
	getFiatDepositURLRequestFieldFailureLink = big.NewInt(1 << 6)
	getFiatDepositURLRequestFieldReturnLink  = big.NewInt(1 << 7)
	getFiatDepositURLRequestFieldRequest     = big.NewInt(1 << 8)
	getFiatDepositURLRequestFieldNonce       = big.NewInt(1 << 9)
)

type GetFiatDepositURLRequest struct {
	// Currency's [ticker](/glossary#ticker) ([fiat](/glossary#fiat)). ⚠️ Currencies ticker should be fiat and has "can_deposit" status must be "true". Use [Asset Status endpoint](/public/http-v4/asset-status-list) to know more about currency.
	Ticker string `json:"ticker" url:"-"`
	// [Fiat](/glossary#fiat) currency [provider](/glossary#provider). ⚠️ Currency provider should be taken from [Asset Status endpoint](/public/http-v4/asset-status-list) response.
	Provider string `json:"provider" url:"-"`
	// Deposit amount
	Amount string `json:"amount" url:"-"`
	// Unique transaction identifier on client's side
	UniqueID *string `json:"unique_id,omitempty" url:"-"`
	// Customer information (required for USD/EUR with VISAMASTER [provider](/glossary#provider))
	Customer *GetFiatDepositURLRequestCustomer `json:"customer,omitempty" url:"-"`
	// Customer will be redirected to this URL by acquiring [provider](/glossary#provider) after success deposit. To activate this feature, please contact support
	SuccessLink *string `json:"successLink,omitempty" url:"-"`
	// Customer will be redirected to this URL in case of fail or rejection on acquiring provider side. To activate this feature, please contact support
	FailureLink *string `json:"failureLink,omitempty" url:"-"`
	// Customer will be redirected to the URL defined if selects 'back' option after from the payment success or failure page. To activate this feature, define desired link. If not populated, option 'back' won't be displayed
	ReturnLink *string `json:"returnLink,omitempty" url:"-"`
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetFiatDepositURLRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetTicker sets the Ticker field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetTicker(ticker string) {
	g.Ticker = ticker
	g.require(getFiatDepositURLRequestFieldTicker)
}

// SetProvider sets the Provider field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetProvider(provider string) {
	g.Provider = provider
	g.require(getFiatDepositURLRequestFieldProvider)
}

// SetAmount sets the Amount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetAmount(amount string) {
	g.Amount = amount
	g.require(getFiatDepositURLRequestFieldAmount)
}

// SetUniqueID sets the UniqueID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetUniqueID(uniqueID *string) {
	g.UniqueID = uniqueID
	g.require(getFiatDepositURLRequestFieldUniqueID)
}

// SetCustomer sets the Customer field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetCustomer(customer *GetFiatDepositURLRequestCustomer) {
	g.Customer = customer
	g.require(getFiatDepositURLRequestFieldCustomer)
}

// SetSuccessLink sets the SuccessLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetSuccessLink(successLink *string) {
	g.SuccessLink = successLink
	g.require(getFiatDepositURLRequestFieldSuccessLink)
}

// SetFailureLink sets the FailureLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetFailureLink(failureLink *string) {
	g.FailureLink = failureLink
	g.require(getFiatDepositURLRequestFieldFailureLink)
}

// SetReturnLink sets the ReturnLink field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetReturnLink(returnLink *string) {
	g.ReturnLink = returnLink
	g.require(getFiatDepositURLRequestFieldReturnLink)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetRequest(request string) {
	g.Request = request
	g.require(getFiatDepositURLRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequest) SetNonce(nonce string) {
	g.Nonce = nonce
	g.require(getFiatDepositURLRequestFieldNonce)
}

func (g *GetFiatDepositURLRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetFiatDepositURLRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetFiatDepositURLRequest(body)
	return nil
}

func (g *GetFiatDepositURLRequest) MarshalJSON() ([]byte, error) {
	type embed GetFiatDepositURLRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	issueCardTokenRequestFieldCardNumber = big.NewInt(1 << 0)
)

type IssueCardTokenRequest struct {
	// Target card number
	CardNumber string `json:"cardNumber" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *IssueCardTokenRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetCardNumber sets the CardNumber field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueCardTokenRequest) SetCardNumber(cardNumber string) {
	i.CardNumber = cardNumber
	i.require(issueCardTokenRequestFieldCardNumber)
}

func (i *IssueCardTokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler IssueCardTokenRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = IssueCardTokenRequest(body)
	return nil
}

func (i *IssueCardTokenRequest) MarshalJSON() ([]byte, error) {
	type embed IssueCardTokenRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	refundDepositRequestFieldTransactionID = big.NewInt(1 << 0)
	refundDepositRequestFieldAddress       = big.NewInt(1 << 1)
	refundDepositRequestFieldRequest       = big.NewInt(1 << 2)
	refundDepositRequestFieldNonce         = big.NewInt(1 << 3)
)

type RefundDepositRequest struct {
	// Transaction UUID of the deposit. Obtain from the [deposit.canceled](/platform/webhook) webhook (`uniqueId` field) or from the deposit/withdraw history in the WhiteBIT interface.
	TransactionID *string `json:"transaction_id,omitempty" url:"-"`
	// Destination wallet address for the refund. The address must support the same network and asset as the original deposit. Cannot be a WhiteBIT address. Does not have to match the original deposit address.
	Address string `json:"address" url:"-"`
	// Base64-encoded request body. See the [authentication guide](/private/http-auth) for signature generation details.
	Request string `json:"request" url:"-"`
	// A unique identifier for the request. Use a monotonically increasing value such as a Unix timestamp in milliseconds.
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (r *RefundDepositRequest) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetTransactionID sets the TransactionID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RefundDepositRequest) SetTransactionID(transactionID *string) {
	r.TransactionID = transactionID
	r.require(refundDepositRequestFieldTransactionID)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RefundDepositRequest) SetAddress(address string) {
	r.Address = address
	r.require(refundDepositRequestFieldAddress)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RefundDepositRequest) SetRequest(request string) {
	r.Request = request
	r.require(refundDepositRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RefundDepositRequest) SetNonce(nonce string) {
	r.Nonce = nonce
	r.require(refundDepositRequestFieldNonce)
}

func (r *RefundDepositRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler RefundDepositRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*r = RefundDepositRequest(body)
	return nil
}

func (r *RefundDepositRequest) MarshalJSON() ([]byte, error) {
	type embed RefundDepositRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

// Address type, available for specific currencies list (see address types table in endpoint description)
type CreateNewAddressRequestType string

const (
	CreateNewAddressRequestTypeP2ShSegwit CreateNewAddressRequestType = "p2sh-segwit"
	CreateNewAddressRequestTypeBech32     CreateNewAddressRequestType = "bech32"
)

func NewCreateNewAddressRequestTypeFromString(s string) (CreateNewAddressRequestType, error) {
	switch s {
	case "p2sh-segwit":
		return CreateNewAddressRequestTypeP2ShSegwit, nil
	case "bech32":
		return CreateNewAddressRequestTypeBech32, nil
	}
	var t CreateNewAddressRequestType
	return "", fmt.Errorf("%s is not a valid %T", s, t)
}

func (c CreateNewAddressRequestType) Ptr() *CreateNewAddressRequestType {
	return &c
}

var (
	createNewAddressResponseFieldAccount  = big.NewInt(1 << 0)
	createNewAddressResponseFieldRequired = big.NewInt(1 << 1)
)

type CreateNewAddressResponse struct {
	Account  *CreateNewAddressResponseAccount  `json:"account,omitempty" url:"account,omitempty"`
	Required *CreateNewAddressResponseRequired `json:"required,omitempty" url:"required,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateNewAddressResponse) GetAccount() *CreateNewAddressResponseAccount {
	if c == nil {
		return nil
	}
	return c.Account
}

func (c *CreateNewAddressResponse) GetRequired() *CreateNewAddressResponseRequired {
	if c == nil {
		return nil
	}
	return c.Required
}

func (c *CreateNewAddressResponse) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateNewAddressResponse) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponse) SetAccount(account *CreateNewAddressResponseAccount) {
	c.Account = account
	c.require(createNewAddressResponseFieldAccount)
}

// SetRequired sets the Required field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponse) SetRequired(required *CreateNewAddressResponseRequired) {
	c.Required = required
	c.require(createNewAddressResponseFieldRequired)
}

func (c *CreateNewAddressResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNewAddressResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateNewAddressResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateNewAddressResponse) MarshalJSON() ([]byte, error) {
	type embed CreateNewAddressResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateNewAddressResponse) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createNewAddressResponseAccountFieldAddress = big.NewInt(1 << 0)
	createNewAddressResponseAccountFieldMemo    = big.NewInt(1 << 1)
)

type CreateNewAddressResponseAccount struct {
	// Deposit address
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Memo if currency requires memo
	Memo *string `json:"memo,omitempty" url:"memo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateNewAddressResponseAccount) GetAddress() *string {
	if c == nil {
		return nil
	}
	return c.Address
}

func (c *CreateNewAddressResponseAccount) GetMemo() *string {
	if c == nil {
		return nil
	}
	return c.Memo
}

func (c *CreateNewAddressResponseAccount) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateNewAddressResponseAccount) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseAccount) SetAddress(address *string) {
	c.Address = address
	c.require(createNewAddressResponseAccountFieldAddress)
}

// SetMemo sets the Memo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseAccount) SetMemo(memo *string) {
	c.Memo = memo
	c.require(createNewAddressResponseAccountFieldMemo)
}

func (c *CreateNewAddressResponseAccount) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNewAddressResponseAccount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateNewAddressResponseAccount(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateNewAddressResponseAccount) MarshalJSON() ([]byte, error) {
	type embed CreateNewAddressResponseAccount
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateNewAddressResponseAccount) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	createNewAddressResponseRequiredFieldMaxAmount = big.NewInt(1 << 0)
	createNewAddressResponseRequiredFieldMinAmount = big.NewInt(1 << 1)
	createNewAddressResponseRequiredFieldFixedFee  = big.NewInt(1 << 2)
	createNewAddressResponseRequiredFieldFlexFee   = big.NewInt(1 << 3)
)

type CreateNewAddressResponseRequired struct {
	// Max amount of deposit accepted by the exchange. Deposits exceeding this amount are rejected.
	MaxAmount *string `json:"maxAmount,omitempty" url:"maxAmount,omitempty"`
	// Min amount of deposit accepted by the exchange. Deposits below this amount are rejected.
	MinAmount *string `json:"minAmount,omitempty" url:"minAmount,omitempty"`
	// Fixed deposit fee
	FixedFee *string `json:"fixedFee,omitempty" url:"fixedFee,omitempty"`
	// Flexible fee - is fee that use percent rate
	FlexFee *CreateNewAddressResponseRequiredFlexFee `json:"flexFee,omitempty" url:"flexFee,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateNewAddressResponseRequired) GetMaxAmount() *string {
	if c == nil {
		return nil
	}
	return c.MaxAmount
}

func (c *CreateNewAddressResponseRequired) GetMinAmount() *string {
	if c == nil {
		return nil
	}
	return c.MinAmount
}

func (c *CreateNewAddressResponseRequired) GetFixedFee() *string {
	if c == nil {
		return nil
	}
	return c.FixedFee
}

func (c *CreateNewAddressResponseRequired) GetFlexFee() *CreateNewAddressResponseRequiredFlexFee {
	if c == nil {
		return nil
	}
	return c.FlexFee
}

func (c *CreateNewAddressResponseRequired) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateNewAddressResponseRequired) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMaxAmount sets the MaxAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequired) SetMaxAmount(maxAmount *string) {
	c.MaxAmount = maxAmount
	c.require(createNewAddressResponseRequiredFieldMaxAmount)
}

// SetMinAmount sets the MinAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequired) SetMinAmount(minAmount *string) {
	c.MinAmount = minAmount
	c.require(createNewAddressResponseRequiredFieldMinAmount)
}

// SetFixedFee sets the FixedFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequired) SetFixedFee(fixedFee *string) {
	c.FixedFee = fixedFee
	c.require(createNewAddressResponseRequiredFieldFixedFee)
}

// SetFlexFee sets the FlexFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequired) SetFlexFee(flexFee *CreateNewAddressResponseRequiredFlexFee) {
	c.FlexFee = flexFee
	c.require(createNewAddressResponseRequiredFieldFlexFee)
}

func (c *CreateNewAddressResponseRequired) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNewAddressResponseRequired
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateNewAddressResponseRequired(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateNewAddressResponseRequired) MarshalJSON() ([]byte, error) {
	type embed CreateNewAddressResponseRequired
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateNewAddressResponseRequired) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

// Flexible fee - is fee that use percent rate
var (
	createNewAddressResponseRequiredFlexFeeFieldMaxFee  = big.NewInt(1 << 0)
	createNewAddressResponseRequiredFlexFeeFieldMinFee  = big.NewInt(1 << 1)
	createNewAddressResponseRequiredFlexFeeFieldPercent = big.NewInt(1 << 2)
)

type CreateNewAddressResponseRequiredFlexFee struct {
	// Maximum fixed fee charged
	MaxFee *string `json:"maxFee,omitempty" url:"maxFee,omitempty"`
	// Minimum fixed fee charged
	MinFee *string `json:"minFee,omitempty" url:"minFee,omitempty"`
	// Percent of deposit as fee
	Percent *string `json:"percent,omitempty" url:"percent,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (c *CreateNewAddressResponseRequiredFlexFee) GetMaxFee() *string {
	if c == nil {
		return nil
	}
	return c.MaxFee
}

func (c *CreateNewAddressResponseRequiredFlexFee) GetMinFee() *string {
	if c == nil {
		return nil
	}
	return c.MinFee
}

func (c *CreateNewAddressResponseRequiredFlexFee) GetPercent() *string {
	if c == nil {
		return nil
	}
	return c.Percent
}

func (c *CreateNewAddressResponseRequiredFlexFee) GetExtraProperties() map[string]interface{} {
	return c.extraProperties
}

func (c *CreateNewAddressResponseRequiredFlexFee) require(field *big.Int) {
	if c.explicitFields == nil {
		c.explicitFields = big.NewInt(0)
	}
	c.explicitFields.Or(c.explicitFields, field)
}

// SetMaxFee sets the MaxFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequiredFlexFee) SetMaxFee(maxFee *string) {
	c.MaxFee = maxFee
	c.require(createNewAddressResponseRequiredFlexFeeFieldMaxFee)
}

// SetMinFee sets the MinFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequiredFlexFee) SetMinFee(minFee *string) {
	c.MinFee = minFee
	c.require(createNewAddressResponseRequiredFlexFeeFieldMinFee)
}

// SetPercent sets the Percent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (c *CreateNewAddressResponseRequiredFlexFee) SetPercent(percent *string) {
	c.Percent = percent
	c.require(createNewAddressResponseRequiredFlexFeeFieldPercent)
}

func (c *CreateNewAddressResponseRequiredFlexFee) UnmarshalJSON(data []byte) error {
	type unmarshaler CreateNewAddressResponseRequiredFlexFee
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*c = CreateNewAddressResponseRequiredFlexFee(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *c)
	if err != nil {
		return err
	}
	c.extraProperties = extraProperties
	c.rawJSON = json.RawMessage(data)
	return nil
}

func (c *CreateNewAddressResponseRequiredFlexFee) MarshalJSON() ([]byte, error) {
	type embed CreateNewAddressResponseRequiredFlexFee
	var marshaler = struct {
		embed
	}{
		embed: embed(*c),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, c.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (c *CreateNewAddressResponseRequiredFlexFee) String() string {
	if len(c.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(c.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(c); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", c)
}

var (
	getDepositAddressResponseFieldAccount  = big.NewInt(1 << 0)
	getDepositAddressResponseFieldRequired = big.NewInt(1 << 1)
)

type GetDepositAddressResponse struct {
	Account  *GetDepositAddressResponseAccount  `json:"account,omitempty" url:"account,omitempty"`
	Required *GetDepositAddressResponseRequired `json:"required,omitempty" url:"required,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetDepositAddressResponse) GetAccount() *GetDepositAddressResponseAccount {
	if g == nil {
		return nil
	}
	return g.Account
}

func (g *GetDepositAddressResponse) GetRequired() *GetDepositAddressResponseRequired {
	if g == nil {
		return nil
	}
	return g.Required
}

func (g *GetDepositAddressResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetDepositAddressResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAccount sets the Account field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponse) SetAccount(account *GetDepositAddressResponseAccount) {
	g.Account = account
	g.require(getDepositAddressResponseFieldAccount)
}

// SetRequired sets the Required field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponse) SetRequired(required *GetDepositAddressResponseRequired) {
	g.Required = required
	g.require(getDepositAddressResponseFieldRequired)
}

func (g *GetDepositAddressResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDepositAddressResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDepositAddressResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDepositAddressResponse) MarshalJSON() ([]byte, error) {
	type embed GetDepositAddressResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetDepositAddressResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getDepositAddressResponseAccountFieldAddress = big.NewInt(1 << 0)
	getDepositAddressResponseAccountFieldMemo    = big.NewInt(1 << 1)
)

type GetDepositAddressResponseAccount struct {
	// Deposit address
	Address *string `json:"address,omitempty" url:"address,omitempty"`
	// Memo if currency requires memo
	Memo *string `json:"memo,omitempty" url:"memo,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetDepositAddressResponseAccount) GetAddress() *string {
	if g == nil {
		return nil
	}
	return g.Address
}

func (g *GetDepositAddressResponseAccount) GetMemo() *string {
	if g == nil {
		return nil
	}
	return g.Memo
}

func (g *GetDepositAddressResponseAccount) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetDepositAddressResponseAccount) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseAccount) SetAddress(address *string) {
	g.Address = address
	g.require(getDepositAddressResponseAccountFieldAddress)
}

// SetMemo sets the Memo field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseAccount) SetMemo(memo *string) {
	g.Memo = memo
	g.require(getDepositAddressResponseAccountFieldMemo)
}

func (g *GetDepositAddressResponseAccount) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDepositAddressResponseAccount
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDepositAddressResponseAccount(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDepositAddressResponseAccount) MarshalJSON() ([]byte, error) {
	type embed GetDepositAddressResponseAccount
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetDepositAddressResponseAccount) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getDepositAddressResponseRequiredFieldFixedFee  = big.NewInt(1 << 0)
	getDepositAddressResponseRequiredFieldFlexFee   = big.NewInt(1 << 1)
	getDepositAddressResponseRequiredFieldMaxAmount = big.NewInt(1 << 2)
	getDepositAddressResponseRequiredFieldMinAmount = big.NewInt(1 << 3)
)

type GetDepositAddressResponseRequired struct {
	// Fixed deposit fee
	FixedFee *string `json:"fixedFee,omitempty" url:"fixedFee,omitempty"`
	// Flexible fee - is fee that use percent rate
	FlexFee *GetDepositAddressResponseRequiredFlexFee `json:"flexFee,omitempty" url:"flexFee,omitempty"`
	// Max amount of deposit accepted by the exchange. Deposits exceeding this amount are rejected.
	MaxAmount *string `json:"maxAmount,omitempty" url:"maxAmount,omitempty"`
	// Min amount of deposit accepted by the exchange. Deposits below this amount are rejected.
	MinAmount *string `json:"minAmount,omitempty" url:"minAmount,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetDepositAddressResponseRequired) GetFixedFee() *string {
	if g == nil {
		return nil
	}
	return g.FixedFee
}

func (g *GetDepositAddressResponseRequired) GetFlexFee() *GetDepositAddressResponseRequiredFlexFee {
	if g == nil {
		return nil
	}
	return g.FlexFee
}

func (g *GetDepositAddressResponseRequired) GetMaxAmount() *string {
	if g == nil {
		return nil
	}
	return g.MaxAmount
}

func (g *GetDepositAddressResponseRequired) GetMinAmount() *string {
	if g == nil {
		return nil
	}
	return g.MinAmount
}

func (g *GetDepositAddressResponseRequired) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetDepositAddressResponseRequired) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetFixedFee sets the FixedFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequired) SetFixedFee(fixedFee *string) {
	g.FixedFee = fixedFee
	g.require(getDepositAddressResponseRequiredFieldFixedFee)
}

// SetFlexFee sets the FlexFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequired) SetFlexFee(flexFee *GetDepositAddressResponseRequiredFlexFee) {
	g.FlexFee = flexFee
	g.require(getDepositAddressResponseRequiredFieldFlexFee)
}

// SetMaxAmount sets the MaxAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequired) SetMaxAmount(maxAmount *string) {
	g.MaxAmount = maxAmount
	g.require(getDepositAddressResponseRequiredFieldMaxAmount)
}

// SetMinAmount sets the MinAmount field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequired) SetMinAmount(minAmount *string) {
	g.MinAmount = minAmount
	g.require(getDepositAddressResponseRequiredFieldMinAmount)
}

func (g *GetDepositAddressResponseRequired) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDepositAddressResponseRequired
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDepositAddressResponseRequired(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDepositAddressResponseRequired) MarshalJSON() ([]byte, error) {
	type embed GetDepositAddressResponseRequired
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetDepositAddressResponseRequired) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Flexible fee - is fee that use percent rate
var (
	getDepositAddressResponseRequiredFlexFeeFieldMaxFee  = big.NewInt(1 << 0)
	getDepositAddressResponseRequiredFlexFeeFieldMinFee  = big.NewInt(1 << 1)
	getDepositAddressResponseRequiredFlexFeeFieldPercent = big.NewInt(1 << 2)
)

type GetDepositAddressResponseRequiredFlexFee struct {
	// Maximum fixed fee charged
	MaxFee *string `json:"maxFee,omitempty" url:"maxFee,omitempty"`
	// Minimum fixed fee charged
	MinFee *string `json:"minFee,omitempty" url:"minFee,omitempty"`
	// Percent of deposit as fee
	Percent *string `json:"percent,omitempty" url:"percent,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetDepositAddressResponseRequiredFlexFee) GetMaxFee() *string {
	if g == nil {
		return nil
	}
	return g.MaxFee
}

func (g *GetDepositAddressResponseRequiredFlexFee) GetMinFee() *string {
	if g == nil {
		return nil
	}
	return g.MinFee
}

func (g *GetDepositAddressResponseRequiredFlexFee) GetPercent() *string {
	if g == nil {
		return nil
	}
	return g.Percent
}

func (g *GetDepositAddressResponseRequiredFlexFee) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetDepositAddressResponseRequiredFlexFee) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetMaxFee sets the MaxFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequiredFlexFee) SetMaxFee(maxFee *string) {
	g.MaxFee = maxFee
	g.require(getDepositAddressResponseRequiredFlexFeeFieldMaxFee)
}

// SetMinFee sets the MinFee field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequiredFlexFee) SetMinFee(minFee *string) {
	g.MinFee = minFee
	g.require(getDepositAddressResponseRequiredFlexFeeFieldMinFee)
}

// SetPercent sets the Percent field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetDepositAddressResponseRequiredFlexFee) SetPercent(percent *string) {
	g.Percent = percent
	g.require(getDepositAddressResponseRequiredFlexFeeFieldPercent)
}

func (g *GetDepositAddressResponseRequiredFlexFee) UnmarshalJSON(data []byte) error {
	type unmarshaler GetDepositAddressResponseRequiredFlexFee
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetDepositAddressResponseRequiredFlexFee(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetDepositAddressResponseRequiredFlexFee) MarshalJSON() ([]byte, error) {
	type embed GetDepositAddressResponseRequiredFlexFee
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetDepositAddressResponseRequiredFlexFee) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

// Customer information (required for USD/EUR with VISAMASTER [provider](/glossary#provider))
var (
	getFiatDepositURLRequestCustomerFieldFirstName = big.NewInt(1 << 0)
	getFiatDepositURLRequestCustomerFieldLastName  = big.NewInt(1 << 1)
	getFiatDepositURLRequestCustomerFieldEmail     = big.NewInt(1 << 2)
	getFiatDepositURLRequestCustomerFieldBirthDate = big.NewInt(1 << 3)
	getFiatDepositURLRequestCustomerFieldAddress   = big.NewInt(1 << 4)
)

type GetFiatDepositURLRequestCustomer struct {
	// Customer billing first name.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	FirstName *string `json:"firstName,omitempty" url:"firstName,omitempty"`
	// Customer billing last name.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	LastName *string `json:"lastName,omitempty" url:"lastName,omitempty"`
	// Customer billing email.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	Email *string `json:"email,omitempty" url:"email,omitempty"`
	// Customer birth date (Format YYYY-MM-DD).
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	BirthDate *time.Time                               `json:"birthDate,omitempty" url:"birthDate,omitempty" format:"date"`
	Address   *GetFiatDepositURLRequestCustomerAddress `json:"address,omitempty" url:"address,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetFiatDepositURLRequestCustomer) GetFirstName() *string {
	if g == nil {
		return nil
	}
	return g.FirstName
}

func (g *GetFiatDepositURLRequestCustomer) GetLastName() *string {
	if g == nil {
		return nil
	}
	return g.LastName
}

func (g *GetFiatDepositURLRequestCustomer) GetEmail() *string {
	if g == nil {
		return nil
	}
	return g.Email
}

func (g *GetFiatDepositURLRequestCustomer) GetBirthDate() *time.Time {
	if g == nil {
		return nil
	}
	return g.BirthDate
}

func (g *GetFiatDepositURLRequestCustomer) GetAddress() *GetFiatDepositURLRequestCustomerAddress {
	if g == nil {
		return nil
	}
	return g.Address
}

func (g *GetFiatDepositURLRequestCustomer) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetFiatDepositURLRequestCustomer) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetFirstName sets the FirstName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomer) SetFirstName(firstName *string) {
	g.FirstName = firstName
	g.require(getFiatDepositURLRequestCustomerFieldFirstName)
}

// SetLastName sets the LastName field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomer) SetLastName(lastName *string) {
	g.LastName = lastName
	g.require(getFiatDepositURLRequestCustomerFieldLastName)
}

// SetEmail sets the Email field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomer) SetEmail(email *string) {
	g.Email = email
	g.require(getFiatDepositURLRequestCustomerFieldEmail)
}

// SetBirthDate sets the BirthDate field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomer) SetBirthDate(birthDate *time.Time) {
	g.BirthDate = birthDate
	g.require(getFiatDepositURLRequestCustomerFieldBirthDate)
}

// SetAddress sets the Address field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomer) SetAddress(address *GetFiatDepositURLRequestCustomerAddress) {
	g.Address = address
	g.require(getFiatDepositURLRequestCustomerFieldAddress)
}

func (g *GetFiatDepositURLRequestCustomer) UnmarshalJSON(data []byte) error {
	type embed GetFiatDepositURLRequestCustomer
	var unmarshaler = struct {
		embed
		BirthDate *internal.Date `json:"birthDate,omitempty"`
	}{
		embed: embed(*g),
	}
	if err := json.Unmarshal(data, &unmarshaler); err != nil {
		return err
	}
	*g = GetFiatDepositURLRequestCustomer(unmarshaler.embed)
	g.BirthDate = unmarshaler.BirthDate.TimePtr()
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetFiatDepositURLRequestCustomer) MarshalJSON() ([]byte, error) {
	type embed GetFiatDepositURLRequestCustomer
	var marshaler = struct {
		embed
		BirthDate *internal.Date `json:"birthDate,omitempty"`
	}{
		embed:     embed(*g),
		BirthDate: internal.NewOptionalDate(g.BirthDate),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetFiatDepositURLRequestCustomer) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getFiatDepositURLRequestCustomerAddressFieldLine1       = big.NewInt(1 << 0)
	getFiatDepositURLRequestCustomerAddressFieldLine2       = big.NewInt(1 << 1)
	getFiatDepositURLRequestCustomerAddressFieldCity        = big.NewInt(1 << 2)
	getFiatDepositURLRequestCustomerAddressFieldZipCode     = big.NewInt(1 << 3)
	getFiatDepositURLRequestCustomerAddressFieldCountryCode = big.NewInt(1 << 4)
)

type GetFiatDepositURLRequestCustomerAddress struct {
	// Customer address line1.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	Line1 *string `json:"line1,omitempty" url:"line1,omitempty"`
	// Customer address line2
	Line2 *string `json:"line2,omitempty" url:"line2,omitempty"`
	// Customer city.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	City *string `json:"city,omitempty" url:"city,omitempty"`
	// Customer zip-code.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	ZipCode *string `json:"zipCode,omitempty" url:"zipCode,omitempty"`
	// Customer country code.
	//
	// ⚠️ Required if currency USD or EUR with VISAMASTER [provider](/glossary#provider).
	CountryCode *string `json:"countryCode,omitempty" url:"countryCode,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetFiatDepositURLRequestCustomerAddress) GetLine1() *string {
	if g == nil {
		return nil
	}
	return g.Line1
}

func (g *GetFiatDepositURLRequestCustomerAddress) GetLine2() *string {
	if g == nil {
		return nil
	}
	return g.Line2
}

func (g *GetFiatDepositURLRequestCustomerAddress) GetCity() *string {
	if g == nil {
		return nil
	}
	return g.City
}

func (g *GetFiatDepositURLRequestCustomerAddress) GetZipCode() *string {
	if g == nil {
		return nil
	}
	return g.ZipCode
}

func (g *GetFiatDepositURLRequestCustomerAddress) GetCountryCode() *string {
	if g == nil {
		return nil
	}
	return g.CountryCode
}

func (g *GetFiatDepositURLRequestCustomerAddress) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetFiatDepositURLRequestCustomerAddress) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetLine1 sets the Line1 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomerAddress) SetLine1(line1 *string) {
	g.Line1 = line1
	g.require(getFiatDepositURLRequestCustomerAddressFieldLine1)
}

// SetLine2 sets the Line2 field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomerAddress) SetLine2(line2 *string) {
	g.Line2 = line2
	g.require(getFiatDepositURLRequestCustomerAddressFieldLine2)
}

// SetCity sets the City field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomerAddress) SetCity(city *string) {
	g.City = city
	g.require(getFiatDepositURLRequestCustomerAddressFieldCity)
}

// SetZipCode sets the ZipCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomerAddress) SetZipCode(zipCode *string) {
	g.ZipCode = zipCode
	g.require(getFiatDepositURLRequestCustomerAddressFieldZipCode)
}

// SetCountryCode sets the CountryCode field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLRequestCustomerAddress) SetCountryCode(countryCode *string) {
	g.CountryCode = countryCode
	g.require(getFiatDepositURLRequestCustomerAddressFieldCountryCode)
}

func (g *GetFiatDepositURLRequestCustomerAddress) UnmarshalJSON(data []byte) error {
	type unmarshaler GetFiatDepositURLRequestCustomerAddress
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetFiatDepositURLRequestCustomerAddress(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetFiatDepositURLRequestCustomerAddress) MarshalJSON() ([]byte, error) {
	type embed GetFiatDepositURLRequestCustomerAddress
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetFiatDepositURLRequestCustomerAddress) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	getFiatDepositURLResponseFieldURL = big.NewInt(1 << 0)
)

type GetFiatDepositURLResponse struct {
	// Address for deposit
	URL *string `json:"url,omitempty" url:"url,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetFiatDepositURLResponse) GetURL() *string {
	if g == nil {
		return nil
	}
	return g.URL
}

func (g *GetFiatDepositURLResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetFiatDepositURLResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetURL sets the URL field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetFiatDepositURLResponse) SetURL(url *string) {
	g.URL = url
	g.require(getFiatDepositURLResponseFieldURL)
}

func (g *GetFiatDepositURLResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetFiatDepositURLResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetFiatDepositURLResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetFiatDepositURLResponse) MarshalJSON() ([]byte, error) {
	type embed GetFiatDepositURLResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetFiatDepositURLResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	refundDepositResponseFieldID = big.NewInt(1 << 0)
)

type RefundDepositResponse struct {
	// Transaction ID of the deposit (echoed from request)
	ID string `json:"id" url:"id"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (r *RefundDepositResponse) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

func (r *RefundDepositResponse) GetExtraProperties() map[string]interface{} {
	return r.extraProperties
}

func (r *RefundDepositResponse) require(field *big.Int) {
	if r.explicitFields == nil {
		r.explicitFields = big.NewInt(0)
	}
	r.explicitFields.Or(r.explicitFields, field)
}

// SetID sets the ID field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (r *RefundDepositResponse) SetID(id string) {
	r.ID = id
	r.require(refundDepositResponseFieldID)
}

func (r *RefundDepositResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler RefundDepositResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*r = RefundDepositResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *r)
	if err != nil {
		return err
	}
	r.extraProperties = extraProperties
	r.rawJSON = json.RawMessage(data)
	return nil
}

func (r *RefundDepositResponse) MarshalJSON() ([]byte, error) {
	type embed RefundDepositResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*r),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, r.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (r *RefundDepositResponse) String() string {
	if len(r.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(r.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(r); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", r)
}
