// Code generated by Fern. DO NOT EDIT.

package api

import (
	json "encoding/json"
	fmt "fmt"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	big "math/big"
)

var (
	getWebSocketTokenRequestFieldRequest = big.NewInt(1 << 0)
	getWebSocketTokenRequestFieldNonce   = big.NewInt(1 << 1)
)

type GetWebSocketTokenRequest struct {
	// Request signature
	Request string `json:"request" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (g *GetWebSocketTokenRequest) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWebSocketTokenRequest) SetRequest(request string) {
	g.Request = request
	g.require(getWebSocketTokenRequestFieldRequest)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWebSocketTokenRequest) SetNonce(nonce string) {
	g.Nonce = nonce
	g.require(getWebSocketTokenRequestFieldNonce)
}

func (g *GetWebSocketTokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler GetWebSocketTokenRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*g = GetWebSocketTokenRequest(body)
	return nil
}

func (g *GetWebSocketTokenRequest) MarshalJSON() ([]byte, error) {
	type embed GetWebSocketTokenRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	issueJwtTokenRequestFieldRequest     = big.NewInt(1 << 0)
	issueJwtTokenRequestFieldNonceWindow = big.NewInt(1 << 1)
	issueJwtTokenRequestFieldNonce       = big.NewInt(1 << 2)
)

type IssueJwtTokenRequest struct {
	// Request signature
	Request string `json:"request" url:"-"`
	// Nonce window setting
	NonceWindow *bool `json:"nonceWindow,omitempty" url:"-"`
	// Unique request identifier
	Nonce string `json:"nonce" url:"-"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`
}

func (i *IssueJwtTokenRequest) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetRequest sets the Request field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueJwtTokenRequest) SetRequest(request string) {
	i.Request = request
	i.require(issueJwtTokenRequestFieldRequest)
}

// SetNonceWindow sets the NonceWindow field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueJwtTokenRequest) SetNonceWindow(nonceWindow *bool) {
	i.NonceWindow = nonceWindow
	i.require(issueJwtTokenRequestFieldNonceWindow)
}

// SetNonce sets the Nonce field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueJwtTokenRequest) SetNonce(nonce string) {
	i.Nonce = nonce
	i.require(issueJwtTokenRequestFieldNonce)
}

func (i *IssueJwtTokenRequest) UnmarshalJSON(data []byte) error {
	type unmarshaler IssueJwtTokenRequest
	var body unmarshaler
	if err := json.Unmarshal(data, &body); err != nil {
		return err
	}
	*i = IssueJwtTokenRequest(body)
	return nil
}

func (i *IssueJwtTokenRequest) MarshalJSON() ([]byte, error) {
	type embed IssueJwtTokenRequest
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

var (
	getWebSocketTokenResponseFieldWebsocketToken = big.NewInt(1 << 0)
)

type GetWebSocketTokenResponse struct {
	// WebSocket authentication token
	WebsocketToken *string `json:"websocket_token,omitempty" url:"websocket_token,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (g *GetWebSocketTokenResponse) GetWebsocketToken() *string {
	if g == nil {
		return nil
	}
	return g.WebsocketToken
}

func (g *GetWebSocketTokenResponse) GetExtraProperties() map[string]interface{} {
	return g.extraProperties
}

func (g *GetWebSocketTokenResponse) require(field *big.Int) {
	if g.explicitFields == nil {
		g.explicitFields = big.NewInt(0)
	}
	g.explicitFields.Or(g.explicitFields, field)
}

// SetWebsocketToken sets the WebsocketToken field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (g *GetWebSocketTokenResponse) SetWebsocketToken(websocketToken *string) {
	g.WebsocketToken = websocketToken
	g.require(getWebSocketTokenResponseFieldWebsocketToken)
}

func (g *GetWebSocketTokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler GetWebSocketTokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*g = GetWebSocketTokenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *g)
	if err != nil {
		return err
	}
	g.extraProperties = extraProperties
	g.rawJSON = json.RawMessage(data)
	return nil
}

func (g *GetWebSocketTokenResponse) MarshalJSON() ([]byte, error) {
	type embed GetWebSocketTokenResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*g),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, g.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (g *GetWebSocketTokenResponse) String() string {
	if len(g.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(g.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(g); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", g)
}

var (
	issueJwtTokenResponseFieldData = big.NewInt(1 << 0)
)

type IssueJwtTokenResponse struct {
	Data *IssueJwtTokenResponseData `json:"data,omitempty" url:"data,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IssueJwtTokenResponse) GetData() *IssueJwtTokenResponseData {
	if i == nil {
		return nil
	}
	return i.Data
}

func (i *IssueJwtTokenResponse) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IssueJwtTokenResponse) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetData sets the Data field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueJwtTokenResponse) SetData(data *IssueJwtTokenResponseData) {
	i.Data = data
	i.require(issueJwtTokenResponseFieldData)
}

func (i *IssueJwtTokenResponse) UnmarshalJSON(data []byte) error {
	type unmarshaler IssueJwtTokenResponse
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IssueJwtTokenResponse(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IssueJwtTokenResponse) MarshalJSON() ([]byte, error) {
	type embed IssueJwtTokenResponse
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IssueJwtTokenResponse) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}

var (
	issueJwtTokenResponseDataFieldToken     = big.NewInt(1 << 0)
	issueJwtTokenResponseDataFieldExpiresAt = big.NewInt(1 << 1)
)

type IssueJwtTokenResponseData struct {
	// JWT token
	Token *string `json:"token,omitempty" url:"token,omitempty"`
	// Token expiration timestamp
	ExpiresAt *int `json:"expires_at,omitempty" url:"expires_at,omitempty"`

	// Private bitmask of fields set to an explicit value and therefore not to be omitted
	explicitFields *big.Int `json:"-" url:"-"`

	extraProperties map[string]interface{}
	rawJSON         json.RawMessage
}

func (i *IssueJwtTokenResponseData) GetToken() *string {
	if i == nil {
		return nil
	}
	return i.Token
}

func (i *IssueJwtTokenResponseData) GetExpiresAt() *int {
	if i == nil {
		return nil
	}
	return i.ExpiresAt
}

func (i *IssueJwtTokenResponseData) GetExtraProperties() map[string]interface{} {
	return i.extraProperties
}

func (i *IssueJwtTokenResponseData) require(field *big.Int) {
	if i.explicitFields == nil {
		i.explicitFields = big.NewInt(0)
	}
	i.explicitFields.Or(i.explicitFields, field)
}

// SetToken sets the Token field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueJwtTokenResponseData) SetToken(token *string) {
	i.Token = token
	i.require(issueJwtTokenResponseDataFieldToken)
}

// SetExpiresAt sets the ExpiresAt field and marks it as non-optional;
// this prevents an empty or null value for this field from being omitted during serialization.
func (i *IssueJwtTokenResponseData) SetExpiresAt(expiresAt *int) {
	i.ExpiresAt = expiresAt
	i.require(issueJwtTokenResponseDataFieldExpiresAt)
}

func (i *IssueJwtTokenResponseData) UnmarshalJSON(data []byte) error {
	type unmarshaler IssueJwtTokenResponseData
	var value unmarshaler
	if err := json.Unmarshal(data, &value); err != nil {
		return err
	}
	*i = IssueJwtTokenResponseData(value)
	extraProperties, err := internal.ExtractExtraProperties(data, *i)
	if err != nil {
		return err
	}
	i.extraProperties = extraProperties
	i.rawJSON = json.RawMessage(data)
	return nil
}

func (i *IssueJwtTokenResponseData) MarshalJSON() ([]byte, error) {
	type embed IssueJwtTokenResponseData
	var marshaler = struct {
		embed
	}{
		embed: embed(*i),
	}
	explicitMarshaler := internal.HandleExplicitFields(marshaler, i.explicitFields)
	return json.Marshal(explicitMarshaler)
}

func (i *IssueJwtTokenResponseData) String() string {
	if len(i.rawJSON) > 0 {
		if value, err := internal.StringifyJSON(i.rawJSON); err == nil {
			return value
		}
	}
	if value, err := internal.StringifyJSON(i); err == nil {
		return value
	}
	return fmt.Sprintf("%#v", i)
}
