// Code generated by Fern. DO NOT EDIT.

package subaccountapikeys

import (
    internal "github.com/whitebit-exchange/go-sdk/internal"
    core "github.com/whitebit-exchange/go-sdk/core"
    context "context"
    gosdk "github.com/whitebit-exchange/go-sdk"
    option "github.com/whitebit-exchange/go-sdk/option"
    http "net/http"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

func (r *RawClient) CreateSubAccountAPIKey(
    ctx context.Context,
    request *gosdk.CreateSubAccountAPIKeyRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.SubAccountAPIKey], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/create"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.SubAccountAPIKey
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.SubAccountAPIKey]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) EditSubAccountAPIKey(
    ctx context.Context,
    request *gosdk.EditSubAccountAPIKeyRequest,
    opts ...option.RequestOption,
) (*core.Response[map[string]any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/edit"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response map[string]any
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[map[string]any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) DeleteSubAccountAPIKey(
    ctx context.Context,
    request *gosdk.DeleteSubAccountAPIKeyRequest,
    opts ...option.RequestOption,
) (*core.Response[map[string]any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/delete"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response map[string]any
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[map[string]any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ListSubAccountAPIKeys(
    ctx context.Context,
    request *gosdk.ListSubAccountAPIKeysRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.ListSubAccountAPIKeysResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/list"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.ListSubAccountAPIKeysResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.ListSubAccountAPIKeysResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ResetSubAccountAPIKey(
    ctx context.Context,
    request *gosdk.ResetSubAccountAPIKeyRequest,
    opts ...option.RequestOption,
) (*core.Response[map[string]any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/reset"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response map[string]any
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[map[string]any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ListSubAccountAPIKeyIPAddresses(
    ctx context.Context,
    request *gosdk.ListSubAccountAPIKeyIPAddressesRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.ListSubAccountAPIKeyIPAddressesResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/ip-address/list"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.ListSubAccountAPIKeyIPAddressesResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.ListSubAccountAPIKeyIPAddressesResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) CreateSubAccountAPIKeyIPAddress(
    ctx context.Context,
    request *gosdk.CreateSubAccountAPIKeyIPAddressRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.CreateSubAccountAPIKeyIPAddressResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/ip-address/create"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.CreateSubAccountAPIKeyIPAddressResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.CreateSubAccountAPIKeyIPAddressResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) DeleteSubAccountAPIKeyIPAddress(
    ctx context.Context,
    request *gosdk.DeleteSubAccountAPIKeyIPAddressRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.DeleteSubAccountAPIKeyIPAddressResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/sub-account/api-key/ip-address/delete"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.DeleteSubAccountAPIKeyIPAddressResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.DeleteSubAccountAPIKeyIPAddressResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

