// Code generated by Fern. DO NOT EDIT.

package crypto_lending_fixed_test

import (
    http "net/http"
    bytes "bytes"
    json "encoding/json"
    os "os"
    testing "testing"
    client "github.com/whitebit-exchange/go-sdk/client"
    option "github.com/whitebit-exchange/go-sdk/option"
    gosdk "github.com/whitebit-exchange/go-sdk"
    context "context"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]string,
    expected int,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            reqBody.WriteString(`":{"equalTo":"`)
            reqBody.WriteString(value)
            reqBody.WriteString(`"}`)
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestCryptoLendingFixedGetFixedPlansWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.GetFixedPlansRequest{
            Ticker: gosdk.String(
                "USDT",
            ),
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.CryptoLendingFixed.GetFixedPlans(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestCryptoLendingFixedGetFixedPlansWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestCryptoLendingFixedGetFixedPlansWithWireMock", "POST", "/api/v4/main-account/smart/plans", nil, 1)
}

func TestCryptoLendingFixedCreateFixedInvestmentWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.CreateFixedInvestmentRequest{
            PlanID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
            Amount: "100",
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.CryptoLendingFixed.CreateFixedInvestment(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestCryptoLendingFixedCreateFixedInvestmentWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestCryptoLendingFixedCreateFixedInvestmentWithWireMock", "POST", "/api/v4/main-account/smart/investment", nil, 1)
}

func TestCryptoLendingFixedCloseFixedInvestmentWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.CloseFixedInvestmentRequest{
            ID: "0d7b66ff-1909-4938-ab7a-d16d9a64dcd5",
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.CryptoLendingFixed.CloseFixedInvestment(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestCryptoLendingFixedCloseFixedInvestmentWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestCryptoLendingFixedCloseFixedInvestmentWithWireMock", "POST", "/api/v4/main-account/smart/investment/close", nil, 1)
}

func TestCryptoLendingFixedGetFixedInvestmentsHistoryWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.GetFixedInvestmentsHistoryRequest{
            ID: gosdk.String(
                "0d7b66ff-1909-4938-ab7a-d16d9a64dcd5",
            ),
            Ticker: gosdk.String(
                "USDT",
            ),
            Status: gosdk.Int(
                1,
            ),
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.CryptoLendingFixed.GetFixedInvestmentsHistory(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestCryptoLendingFixedGetFixedInvestmentsHistoryWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestCryptoLendingFixedGetFixedInvestmentsHistoryWithWireMock", "POST", "/api/v4/main-account/smart/investments", nil, 1)
}

func TestCryptoLendingFixedGetInterestPaymentHistoryWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.GetInterestPaymentHistoryRequest{
            PlanID: gosdk.String(
                "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
            ),
            Ticker: gosdk.String(
                "USDT",
            ),
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.CryptoLendingFixed.GetInterestPaymentHistory(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestCryptoLendingFixedGetInterestPaymentHistoryWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestCryptoLendingFixedGetInterestPaymentHistoryWithWireMock", "POST", "/api/v4/main-account/smart/interest-payment-history", nil, 1)
}


