// Code generated by Fern. DO NOT EDIT.

package jwt

import (
	context "context"
	sdk "github.com/whitebit-exchange/go-sdk"
	core "github.com/whitebit-exchange/go-sdk/core"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	option "github.com/whitebit-exchange/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// The endpoint issues a JWT token for the Fiat Gateway service.
// The token is used to authenticate requests to the Fiat Gateway API.
//
// <Note>
// The API does not cache the response.
// </Note>
func (c *Client) IssueJwtToken(
	ctx context.Context,
	request *sdk.IssueJwtTokenRequest,
	opts ...option.RequestOption,
) (*sdk.IssueJwtTokenResponse, error) {
	response, err := c.WithRawResponse.IssueJwtToken(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The V4 endpoint can be used to retrieve the WebSocket token for user.
// The token is required to authorize WebSocket connections for private API access.
//
// <Accordion title="Errors">
// ```json
//
//	{
//	  "code": 30,
//	  "message": "Validation failed",
//	  "errors": {
//	    "user": ["user not found"]
//	  }
//	}
//
// ```
// </Accordion>
//
// Beyond the error above, this endpoint can return only the [common authentication errors](/api-reference/authentication).
//
// <Warning>
// Rate limit: 10 requests/60 sec.
// </Warning>
//
// <Note>
// The API does not cache the response.
// </Note>
func (c *Client) GetWebSocketToken(
	ctx context.Context,
	request *sdk.GetWebSocketTokenRequest,
	opts ...option.RequestOption,
) (*sdk.GetWebSocketTokenResponse, error) {
	response, err := c.WithRawResponse.GetWebSocketToken(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
