// Code generated by Fern. DO NOT EDIT.

package withdraw_test

import (
    http "net/http"
    bytes "bytes"
    json "encoding/json"
    os "os"
    testing "testing"
    client "github.com/whitebit-exchange/go-sdk/client"
    option "github.com/whitebit-exchange/go-sdk/option"
    gosdk "github.com/whitebit-exchange/go-sdk"
    context "context"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]string,
    expected int,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            reqBody.WriteString(`":{"equalTo":"`)
            reqBody.WriteString(value)
            reqBody.WriteString(`"}`)
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestWithdrawCreateWithdrawWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.CreateWithdrawRequest{
            Ticker: "ETH",
            Amount: "0.9",
            Address: "0x0964A6B8F794A4B8d61b62652dB27ddC9844FB4c",
            UniqueID: gosdk.String(
                "24529041",
            ),
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.Withdraw.CreateWithdraw(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWithdrawCreateWithdrawWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWithdrawCreateWithdrawWithWireMock", "POST", "/api/v4/main-account/withdraw", nil, 1)
}

func TestWithdrawCreateWithdrawPayWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.WithdrawRequest{
            Ticker: "ETH",
            Amount: "0.9",
            Address: "0x0964A6B8F794A4B8d61b62652dB27ddC9844FB4c",
            UniqueID: gosdk.String(
                "24529041",
            ),
            Request: "{{request}}",
            Nonce: "{{nonce}}",
        }
    _, invocationErr :=     client.Withdraw.CreateWithdrawPay(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestWithdrawCreateWithdrawPayWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestWithdrawCreateWithdrawPayWithWireMock", "POST", "/api/v4/main-account/withdraw-pay", nil, 1)
}


