// Code generated by Fern. DO NOT EDIT.

package publicapiv4

import (
	context "context"
	sdk "github.com/whitebit-exchange/go-sdk"
	core "github.com/whitebit-exchange/go-sdk/core"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	option "github.com/whitebit-exchange/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// The endpoint retrieves the current maintenance status of the WhiteBIT platform. Use the response to detect scheduled downtime and pause trading automation during maintenance windows. The `status` field returns `"system operational"` when all platform services are available, or `"system maintenance"` when the platform is undergoing planned maintenance.
func (c *Client) MaintenanceStatus(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetAPIV4PublicPlatformStatusResponse, error) {
	response, err := c.WithRawResponse.MaintenanceStatus(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves configuration and trading rules for all available spot and futures markets (TradFi futures markets are coming soon and are not yet returned). Use the response to discover tradeable pairs, check minimum order sizes, and read fee schedules. Each entry includes precision settings, fee ratios, and order-size constraints for the market.
//
// <Note>
// Market configuration is reference data, re-synced from the database approximately every 10 seconds. Polling more frequently returns identical data. The cache is shared across all callers.
// </Note>
//
// <Note>
// TradFi futures markets are coming soon and are not yet returned by this endpoint. Once available, they will be region-gated: markets not available in a given region are omitted from the response entirely and do not appear under any other market type.
// </Note>
//
// <Note>
// A market with an announced delisting carries the announced date in `delistedAt` and stays tradeable until the delisting runs. Once the delisting runs, the platform cancels the active orders on the market and drops the market from this response — [Query delisting orders](/api-reference/spot-trading/query-delisting-orders) is a signed request that returns the authenticated account's resulting spot order records. An announcement can be rescheduled or canceled, so treat `delistedAt` as the current plan rather than a settled fact and re-read the value on the next poll.
// </Note>
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
func (c *Client) MarketInfo(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]*sdk.GetAPIV4PublicMarketsResponseItem, error) {
	response, err := c.WithRawResponse.MarketInfo(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves a 24-hour pricing and volume summary for each market pair available on the exchange.
//
// <Note>
// The API caches the response for 1 second
// </Note>
//
// <Warning>
// Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
// </Warning>
func (c *Client) MarketActivity(
	ctx context.Context,
	opts ...option.RequestOption,
) (map[string]*sdk.GetAPIV4PublicTickerResponseValue, error) {
	response, err := c.WithRawResponse.MarketActivity(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves the deposit and withdrawal status for every supported asset. Use the response to check whether deposits and withdrawals are enabled, read per-network fee and limit details, and determine required blockchain confirmation counts. The response includes crypto assets, fiat currencies, and fiat payment methods.
//
// <Note>
// Asset status is reference data, re-synced approximately once per minute. Polling more frequently returns identical data. The cache is shared across all callers.
// </Note>
//
// <Warning>
// Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
// </Warning>
func (c *Client) AssetStatusList(
	ctx context.Context,
	opts ...option.RequestOption,
) (map[string]*sdk.Asset, error) {
	response, err := c.WithRawResponse.AssetStatusList(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves the current [order book](/glossary#order-book) as two arrays ([bids](/glossary#bid) / [asks](/glossary#ask)) with additional parameters.
//
// <Note>
// The API caches the response for 100 ms
// </Note>
//
// <Warning>
// Rate limit 600 requests/10 sec.
// </Warning>
func (c *Client) Orderbook(
	ctx context.Context,
	request *sdk.GetAPIV4PublicOrderbookMarketRequest,
	opts ...option.RequestOption,
) (*sdk.OrderbookResponse, error) {
	response, err := c.WithRawResponse.Orderbook(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves depth price levels within ±2% of the market last price. Use when lightweight order book data is needed for a narrow price band around the current market price. The ±2% constraint limits the response to price levels near the last traded price, reducing payload size compared to the full order book.
//
// <Note>
// The API caches the response for 1 sec
// </Note>
//
// <Warning>
// Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
// </Warning>
func (c *Client) Depth(
	ctx context.Context,
	request *sdk.GetAPIV4PublicOrderbookDepthMarketRequest,
	opts ...option.RequestOption,
) (*sdk.OrderbookResponse, error) {
	response, err := c.WithRawResponse.Depth(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves the [trades](/glossary#deal-trade) that have been executed recently on the requested [market](/glossary#market). It returns up to the 100 most recent trades; the response size is fixed and there is no `limit` parameter.
//
// <Note>
// The API caches the response for 1 second
// </Note>
//
// <Note>
//
//	Public trade data can include executions that originate from RPI orders. Public order book feeds (`depth`, `bookTicker`) exclude RPI orders. RPI orders appear only in private active orders and in the exchange UI order book (web and mobile).
//
// </Note>
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
func (c *Client) RecentTrades(
	ctx context.Context,
	request *sdk.GetAPIV4PublicTradesMarketRequest,
	opts ...option.RequestOption,
) ([]*sdk.GetAPIV4PublicTradesMarketResponseItem, error) {
	response, err := c.WithRawResponse.RecentTrades(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves the [fee](/glossary#fee) schedule and deposit/withdrawal limits for every supported asset. Use the response to display fee estimates before a user initiates a deposit or withdrawal. The response is keyed by currency ticker; each entry contains deposit and withdrawal fee amounts and min/max transfer limits.
//
// <Note>
// The fee schedule is reference data, re-synced approximately once per minute. Polling more frequently returns identical data. The cache is shared across all callers.
// </Note>
//
// <Warning>
// Rate limit: 2000 requests/10 sec. See [Public API V4 overview](/public/http-v4/index) for rate limit details.
// </Warning>
func (c *Client) Fee(
	ctx context.Context,
	opts ...option.RequestOption,
) (map[string]*sdk.FeeInfo, error) {
	response, err := c.WithRawResponse.Fee(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint retrieves the current server time as a Unix timestamp. Use the response to synchronize local clocks before generating HMAC signatures for authenticated requests. The endpoint takes no parameters and has no request-validation errors; it returns HTTP 200 on success and fails only at the infrastructure level (see the API description).
//
// <Note>
// The server time is computed per request and is not cached.
// </Note>
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
func (c *Client) ServerTime(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetAPIV4PublicTimeResponse, error) {
	response, err := c.WithRawResponse.ServerTime(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint checks API availability by returning a simple health-check response. Use the endpoint to verify network connectivity and confirm the API server is reachable. A successful response contains the string `"pong"`. The endpoint takes no parameters and has no request-validation errors; it returns HTTP 200 on success and fails only at the infrastructure level (see the API description).
//
// <Note>
// The health-check response is generated per request and is not cached.
// </Note>
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
func (c *Client) ServerStatus(
	ctx context.Context,
	opts ...option.RequestOption,
) ([]string, error) {
	response, err := c.WithRawResponse.ServerStatus(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint returns the list of [market](/glossary#market) pair names available for [collateral](/glossary#collateral) trading. Use the response to determine which markets support margin positions. Each item in the result array is a market pair name in `BASE_QUOTE` format (e.g., `BTC_USDT`).
//
// <Note>
// The collateral market list is reference data, re-synced approximately every 10 seconds. Polling more frequently returns identical data. The cache is shared across all callers.
// </Note>
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
func (c *Client) CollateralMarketsList(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetAPIV4PublicCollateralMarketsResponse, error) {
	response, err := c.WithRawResponse.CollateralMarketsList(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint returns detailed information for all available futures markets. Use the response to read current pricing, open interest, funding rates, and leverage bracket configuration. Each entry includes the predicted next funding rate, settlement timestamps, and maximum allowed position sizes per leverage level.
//
// <Note>
// The API caches the response for 1 second
// </Note>
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
func (c *Client) AvailableFuturesMarketsList(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetAPIV4PublicFuturesResponse, error) {
	response, err := c.WithRawResponse.AvailableFuturesMarketsList(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint returns the funding rate history for a specified futures market. Use the response to analyze historical funding rate trends and settlement prices. Results are sorted by funding time in descending order and support offset-based pagination via `limit` and `offset` parameters.
//
// <Warning>
// Rate limit 2000 requests/10 sec.
// </Warning>
//
// <Note>
// This endpoint supports pagination. Use `limit` (default: 100, max: 100) and `offset` (default: 0, max: 1000000) to page through results.
// </Note>
//
// <Note>
// The response is a plain array with no `total`, `has_more`, or cursor — a returned count below `limit` marks the last page (an empty array means no further records).
// </Note>
//
// <Note>
// Funding history is served per request at the API layer, with no application-level cache.
// </Note>
func (c *Client) FundingHistory(
	ctx context.Context,
	request *sdk.GetAPIV4PublicFundingHistoryMarketRequest,
	opts ...option.RequestOption,
) ([]*sdk.GetAPIV4PublicFundingHistoryMarketResponseItem, error) {
	response, err := c.WithRawResponse.FundingHistory(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint returns overall information about the current mining pool state.
//
// Hash rate is expressed in H units.
//
// <Warning>
// Rate limit 1000 requests/10 sec.
// </Warning>
func (c *Client) MiningPoolOverview(
	ctx context.Context,
	opts ...option.RequestOption,
) (*sdk.GetAPIV4PublicMiningPoolResponse, error) {
	response, err := c.WithRawResponse.MiningPoolOverview(
		ctx,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
