// Code generated by Fern. DO NOT EDIT.

package publicapiv4

import (
    internal "github.com/whitebit-exchange/go-sdk/internal"
    core "github.com/whitebit-exchange/go-sdk/core"
    context "context"
    option "github.com/whitebit-exchange/go-sdk/option"
    gosdk "github.com/whitebit-exchange/go-sdk"
    http "net/http"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

func (r *RawClient) MaintenanceStatus(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetAPIV4PublicPlatformStatusResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/platform/status"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.GetAPIV4PublicPlatformStatusResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetAPIV4PublicPlatformStatusResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) MarketInfo(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[[]*gosdk.GetAPIV4PublicMarketsResponseItem], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/markets"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response []*gosdk.GetAPIV4PublicMarketsResponseItem
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[[]*gosdk.GetAPIV4PublicMarketsResponseItem]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) MarketActivity(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[map[string]*gosdk.GetAPIV4PublicTickerResponseValue], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/ticker"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response map[string]*gosdk.GetAPIV4PublicTickerResponseValue
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[map[string]*gosdk.GetAPIV4PublicTickerResponseValue]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) AssetStatusList(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[map[string]*gosdk.Asset], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/assets"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response map[string]*gosdk.Asset
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[map[string]*gosdk.Asset]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Orderbook(
    ctx context.Context,
    request *gosdk.GetAPIV4PublicOrderbookMarketRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.OrderbookResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/api/v4/public/orderbook/%v",
        request.Market,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.OrderbookResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.OrderbookResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Depth(
    ctx context.Context,
    request *gosdk.GetAPIV4PublicOrderbookDepthMarketRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.OrderbookResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/api/v4/public/orderbook/depth/%v",
        request.Market,
    )
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.OrderbookResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.OrderbookResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) RecentTrades(
    ctx context.Context,
    request *gosdk.GetAPIV4PublicTradesMarketRequest,
    opts ...option.RequestOption,
) (*core.Response[[]*gosdk.GetAPIV4PublicTradesMarketResponseItem], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/api/v4/public/trades/%v",
        request.Market,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response []*gosdk.GetAPIV4PublicTradesMarketResponseItem
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[[]*gosdk.GetAPIV4PublicTradesMarketResponseItem]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) Fee(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[map[string]any], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/fee"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response map[string]any
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[map[string]any]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ServerTime(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetAPIV4PublicTimeResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/time"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.GetAPIV4PublicTimeResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetAPIV4PublicTimeResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ServerStatus(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[[]string], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/ping"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response []string
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[[]string]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) CollateralMarketsList(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetAPIV4PublicCollateralMarketsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/collateral/markets"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.GetAPIV4PublicCollateralMarketsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetAPIV4PublicCollateralMarketsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) AvailableFuturesMarketsList(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetAPIV4PublicFuturesResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/futures"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.GetAPIV4PublicFuturesResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetAPIV4PublicFuturesResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) FundingHistory(
    ctx context.Context,
    request *gosdk.GetAPIV4PublicFundingHistoryMarketRequest,
    opts ...option.RequestOption,
) (*core.Response[[]*gosdk.GetAPIV4PublicFundingHistoryMarketResponseItem], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := internal.EncodeURL(
        baseURL + "/api/v4/public/funding-history/%v",
        request.Market,
    )
    queryParams, err := internal.QueryValues(request)
    if err != nil {
        return nil, err
    }
    if len(queryParams) > 0 {
        endpointURL += "?" + queryParams.Encode()
    }
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response []*gosdk.GetAPIV4PublicFundingHistoryMarketResponseItem
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[[]*gosdk.GetAPIV4PublicFundingHistoryMarketResponseItem]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) MiningPoolOverview(
    ctx context.Context,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetAPIV4PublicMiningPoolResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/public/mining-pool"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    var response *gosdk.GetAPIV4PublicMiningPoolResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodGet,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Response: &response,
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetAPIV4PublicMiningPoolResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

