// Code generated by Fern. DO NOT EDIT.

package root_test

import (
    http "net/http"
    bytes "bytes"
    json "encoding/json"
    os "os"
    testing "testing"
    client "github.com/whitebit-exchange/go-sdk/client"
    option "github.com/whitebit-exchange/go-sdk/option"
    gosdk "github.com/whitebit-exchange/go-sdk"
    context "context"
    require "github.com/stretchr/testify/require"
)



func VerifyRequestCount(
    t *testing.T,
    testId string,
    method string,
    urlPath string,
    queryParams map[string]string,
    expected int,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
    var reqBody bytes.Buffer
    reqBody.WriteString(`{"method":"`)
    reqBody.WriteString(method)
    reqBody.WriteString(`","urlPath":"`)
    reqBody.WriteString(urlPath)
    reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
    reqBody.WriteString(testId)
    reqBody.WriteString(`"}}`)
    if len(queryParams) > 0 {
        reqBody.WriteString(`,"queryParameters":{`)
        first := true
        for key, value := range queryParams {
            if !first {
                reqBody.WriteString(",")
            }
            reqBody.WriteString(`"`)
            reqBody.WriteString(key)
            reqBody.WriteString(`":{"equalTo":"`)
            reqBody.WriteString(value)
            reqBody.WriteString(`"}`)
            first = false
        }
        reqBody.WriteString("}")
    }
    reqBody.WriteString("}")
    resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
    require.NoError(t, err)
    var result struct { Requests []interface{} `json:"requests"` }
    json.NewDecoder(resp.Body).Decode(&result)
    require.Equal(t, expected, len(result.Requests))
}

func TestConvertEstimateWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.ConvertEstimateRequest{
            From: "BTC",
            To: "USDT",
            Direction: gosdk.ConvertEstimateRequestDirectionTo,
            Amount: "35,103.1",
        }
    _, invocationErr :=     client.ConvertEstimate(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestConvertEstimateWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestConvertEstimateWithWireMock", "POST", "/api/v4/convert/estimate", nil, 1)
}

func TestConvertConfirmWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.ConvertConfirmRequest{
            QuoteID: "4050",
        }
    _, invocationErr :=     client.ConvertConfirm(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestConvertConfirmWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestConvertConfirmWithWireMock", "POST", "/api/v4/convert/confirm", nil, 1)
}

func TestConvertHistoryWithWireMock(
    t *testing.T,
) {
    wiremockPort := os.Getenv("WIREMOCK_PORT")
    	if wiremockPort == "" {
    		wiremockPort = "8080"
    	}
    	WireMockBaseURL := "http://localhost:" + wiremockPort
    client := client.NewClient(
        option.WithBaseURL(WireMockBaseURL),
    )
        request := &gosdk.ConvertHistoryRequest{
            FromTicker: gosdk.String(
                "BTC",
            ),
        }
    _, invocationErr :=     client.ConvertHistory(
            context.TODO(),
            request,
            option.WithHTTPHeader(
                http.Header{"X-Test-Id": []string{"TestConvertHistoryWithWireMock"}},
            ),
        )

    require.NoError(t, invocationErr, "Client method call should succeed")
    VerifyRequestCount(t, "TestConvertHistoryWithWireMock", "POST", "/api/v4/convert/history", nil, 1)
}


