// Code generated by Fern. DO NOT EDIT.

package sub_account_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/whitebit-exchange/go-sdk"
	client "github.com/whitebit-exchange/go-sdk/client"
	option "github.com/whitebit-exchange/go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestSubAccountCreateSubAccountWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.CreateSubAccountRequest{
		Alias: "trading_bot",
		Permissions: &sdk.CreateSubAccountRequestPermissions{
			SpotEnabled:       true,
			CollateralEnabled: false,
		},
	}
	_, invocationErr := client.SubAccount.CreateSubAccount(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountCreateSubAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountCreateSubAccountWithWireMock", "POST", "/api/v4/sub-account/create", nil, 1)
}

func TestSubAccountDeleteSubAccountWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.DeleteSubAccountRequest{
		ID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
	}
	_, invocationErr := client.SubAccount.DeleteSubAccount(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountDeleteSubAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountDeleteSubAccountWithWireMock", "POST", "/api/v4/sub-account/delete", nil, 1)
}

func TestSubAccountEditSubAccountWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.EditSubAccountRequest{
		ID:    "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
		Alias: "training",
		Permissions: &sdk.EditSubAccountRequestPermissions{
			SpotEnabled:       true,
			CollateralEnabled: false,
		},
	}
	_, invocationErr := client.SubAccount.EditSubAccount(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountEditSubAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountEditSubAccountWithWireMock", "POST", "/api/v4/sub-account/edit", nil, 1)
}

func TestSubAccountListSubAccountsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ListSubAccountsRequest{}
	_, invocationErr := client.SubAccount.ListSubAccounts(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountListSubAccountsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountListSubAccountsWithWireMock", "POST", "/api/v4/sub-account/list", nil, 1)
}

func TestSubAccountTransferWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SubAccountTransferRequest{
		ID:        "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
		Direction: sdk.SubAccountTransferRequestDirectionMainToSub,
		Amount:    "0.5",
		Ticker:    "ETH",
	}
	_, invocationErr := client.SubAccount.Transfer(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountTransferWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountTransferWithWireMock", "POST", "/api/v4/sub-account/transfer", nil, 1)
}

func TestSubAccountBlockSubAccountWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.BlockSubAccountRequest{
		ID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
	}
	_, invocationErr := client.SubAccount.BlockSubAccount(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountBlockSubAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountBlockSubAccountWithWireMock", "POST", "/api/v4/sub-account/block", nil, 1)
}

func TestSubAccountUnblockSubAccountWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.UnblockSubAccountRequest{
		ID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
	}
	_, invocationErr := client.SubAccount.UnblockSubAccount(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountUnblockSubAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountUnblockSubAccountWithWireMock", "POST", "/api/v4/sub-account/unblock", nil, 1)
}

func TestSubAccountGetSubAccountBalancesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetSubAccountBalancesRequest{
		ID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
		Ticker: sdk.String(
			"USDC",
		),
	}
	_, invocationErr := client.SubAccount.GetSubAccountBalances(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountGetSubAccountBalancesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountGetSubAccountBalancesWithWireMock", "POST", "/api/v4/sub-account/balances", nil, 1)
}

func TestSubAccountGetSubAccountTransferHistoryWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetSubAccountTransferHistoryRequest{
		ID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
	}
	_, invocationErr := client.SubAccount.GetSubAccountTransferHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountGetSubAccountTransferHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountGetSubAccountTransferHistoryWithWireMock", "POST", "/api/v4/sub-account/transfer/history", nil, 1)
}

func TestSubAccountListUnconfirmedSubAccountWithdrawalsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ListUnconfirmedSubAccountWithdrawalsRequest{
		Limit: sdk.Int(
			100,
		),
		Offset: sdk.Int(
			0,
		),
	}
	_, invocationErr := client.SubAccount.ListUnconfirmedSubAccountWithdrawals(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountListUnconfirmedSubAccountWithdrawalsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountListUnconfirmedSubAccountWithdrawalsWithWireMock", "POST", "/api/v4/sub-account/withdraw/unconfirmed-list", nil, 1)
}

func TestSubAccountConfirmSubAccountWithdrawalWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ConfirmSubAccountWithdrawalRequest{
		ID: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
	}
	_, invocationErr := client.SubAccount.ConfirmSubAccountWithdrawal(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountConfirmSubAccountWithdrawalWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountConfirmSubAccountWithdrawalWithWireMock", "POST", "/api/v4/sub-account/withdraw/confirm", nil, 1)
}

func TestSubAccountGetSubAccountKycURLWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetSubAccountKycURLRequest{
		ID: "8e667b4a-0b71-4988-8af5-9474dbfaeb51",
	}
	_, invocationErr := client.SubAccount.GetSubAccountKycURL(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestSubAccountGetSubAccountKycURLWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestSubAccountGetSubAccountKycURLWithWireMock", "POST", "/api/v4/sub-account/kyc-url", nil, 1)
}
