// Code generated by Fern. DO NOT EDIT.

package miningpool

import (
	context "context"
	sdk "github.com/whitebit-exchange/go-sdk"
	core "github.com/whitebit-exchange/go-sdk/core"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	option "github.com/whitebit-exchange/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// The endpoint returns rewards received from mining.
// Results are ordered by reward date, newest first.
//
// The response does not include a `total` field. Detect the last page when
// `data.length < limit`.
//
// The `offset` parameter is capped at 10000. To paginate reward histories
// beyond that, window the request by `from` and `to` (Unix timestamps).
//
// <Note>
// The `account` filter is not validated at the request layer. An unknown or
// not-owned account name is treated as an empty filter and returns HTTP `200`
// with an empty `data` array — the same response as a valid account with no
// rewards in the requested window. An account without mining access also
// returns empty data, so an empty response does not distinguish "no mining
// access" from "no rewards in range."
// </Note>
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
//
// <Note>
// The API does not cache the response.
// </Note>
func (c *Client) GetMiningRewards(
	ctx context.Context,
	request *sdk.GetMiningRewardsRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningRewardsResponse, error) {
	response, err := c.WithRawResponse.GetMiningRewards(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// The endpoint returns hashrate of mining pool account.
//
// <Note>
// There is no dedicated "mining not enabled" error. An account that is
// administratively disabled for mining returns HTTP `200` with empty data
// rather than an error.
// </Note>
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
//
// <Note>
// The API does not cache the response.
// </Note>
func (c *Client) GetMiningHashrate(
	ctx context.Context,
	request *sdk.GetMiningHashrateRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningHashrateResponse, error) {
	response, err := c.WithRawResponse.GetMiningHashrate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns the current payout destination setting for a specific mining account belonging to the authenticated user.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) GetMiningPayoutDestination(
	ctx context.Context,
	request *sdk.GetMiningPayoutDestinationRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningPayoutDestinationResponse, error) {
	response, err := c.WithRawResponse.GetMiningPayoutDestination(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Updates the payout destination for a specific mining account belonging to the authenticated user. Can be set to main balance or an external BTC address.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) SetMiningPayoutDestination(
	ctx context.Context,
	request *sdk.SetMiningPayoutDestinationRequest,
	opts ...option.RequestOption,
) (*sdk.SetMiningPayoutDestinationResponse, error) {
	response, err := c.WithRawResponse.SetMiningPayoutDestination(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns fee information and stratum connection details with worker counts for a specific mining account.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) GetMiningMinerInfo(
	ctx context.Context,
	request *sdk.GetMiningMinerInfoRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningMinerInfoResponse, error) {
	response, err := c.WithRawResponse.GetMiningMinerInfo(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a paginated list of online worker names for a specific mining account.
// Results are ordered by worker name ascending (alphabetical).
//
// The response does not include a `total` field. Detect the last page when
// `data.workers.length < limit`.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) GetMiningWorkerNames(
	ctx context.Context,
	request *sdk.GetMiningWorkerNamesRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningWorkerNamesResponse, error) {
	response, err := c.WithRawResponse.GetMiningWorkerNames(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns hashrate performance history for a specific worker on a mining account.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) GetMiningWorkerHashrate(
	ctx context.Context,
	request *sdk.GetMiningWorkerHashrateRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningWorkerHashrateResponse, error) {
	response, err := c.WithRawResponse.GetMiningWorkerHashrate(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new watcher link for one or more mining accounts, granting specific permissions with a configurable expiration.
//
// <Note>
// The number of active watcher links per mining account is capped (configurable
// server-side; currently 3 by default). Exceeding the cap returns a `400` with
// `Limit exceeded`.
// </Note>
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) CreateMiningWatcherLink(
	ctx context.Context,
	request *sdk.CreateMiningWatcherLinkRequest,
	opts ...option.RequestOption,
) (*sdk.CreateMiningWatcherLinkResponse, error) {
	response, err := c.WithRawResponse.CreateMiningWatcherLink(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns all active watcher links for a specific mining account.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) ListMiningWatcherLinks(
	ctx context.Context,
	request *sdk.ListMiningWatcherLinksRequest,
	opts ...option.RequestOption,
) (*sdk.ListMiningWatcherLinksResponse, error) {
	response, err := c.WithRawResponse.ListMiningWatcherLinks(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Creates a new mining account for the authenticated user. The account name must be unique within the user's accounts.
//
// <Note>
// The number of mining accounts per user is capped (configurable server-side).
// Creating an account beyond the cap returns a `400` with
// `miningPool.validation.maxAccounts`.
// </Note>
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) CreateMiningAccount(
	ctx context.Context,
	request *sdk.CreateMiningAccountRequest,
	opts ...option.RequestOption,
) (*sdk.CreateMiningAccountResponse, error) {
	response, err := c.WithRawResponse.CreateMiningAccount(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Returns a list of mining accounts for the authenticated user. Supports filtering by account name.
// Results are ordered by account creation time, newest first.
//
// The response does not include a `total` field. Detect the last page when
// `data.length < limit`.
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) GetMiningAccounts(
	ctx context.Context,
	request *sdk.GetMiningAccountsRequest,
	opts ...option.RequestOption,
) (*sdk.GetMiningAccountsResponse, error) {
	response, err := c.WithRawResponse.GetMiningAccounts(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
