// Code generated by Fern. DO NOT EDIT.

package miningpool

import (
    internal "github.com/whitebit-exchange/go-sdk/internal"
    core "github.com/whitebit-exchange/go-sdk/core"
    context "context"
    gosdk "github.com/whitebit-exchange/go-sdk"
    option "github.com/whitebit-exchange/go-sdk/option"
    http "net/http"
)


type RawClient struct {
    baseURL string
    caller *internal.Caller
    options *core.RequestOptions
}

func NewRawClient(options *core.RequestOptions) *RawClient {
    return &RawClient{
        options: options,
        baseURL: options.BaseURL,
        caller: internal.NewCaller(
            &internal.CallerParams{
                Client: options.HTTPClient,
                MaxAttempts: options.MaxAttempts,
            },
        ),
    }
}

func (r *RawClient) GetMiningRewards(
    ctx context.Context,
    request *gosdk.GetMiningRewardsRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningRewardsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/rewards"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningRewardsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningRewardsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetMiningHashrate(
    ctx context.Context,
    request *gosdk.GetMiningHashrateRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningHashrateResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/hashrate"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningHashrateResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningHashrateResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetMiningPayoutDestination(
    ctx context.Context,
    request *gosdk.GetMiningPayoutDestinationRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningPayoutDestinationResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/payout-destination"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningPayoutDestinationResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningPayoutDestinationResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) SetMiningPayoutDestination(
    ctx context.Context,
    request *gosdk.SetMiningPayoutDestinationRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.SetMiningPayoutDestinationResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/payout-destination/edit"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.SetMiningPayoutDestinationResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.SetMiningPayoutDestinationResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetMiningMinerInfo(
    ctx context.Context,
    request *gosdk.GetMiningMinerInfoRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningMinerInfoResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/miners/info"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningMinerInfoResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningMinerInfoResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetMiningWorkerNames(
    ctx context.Context,
    request *gosdk.GetMiningWorkerNamesRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningWorkerNamesResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/workers/names"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningWorkerNamesResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningWorkerNamesResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetMiningWorkerHashrate(
    ctx context.Context,
    request *gosdk.GetMiningWorkerHashrateRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningWorkerHashrateResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/workers/hashrate"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningWorkerHashrateResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningWorkerHashrateResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) CreateMiningWatcherLink(
    ctx context.Context,
    request *gosdk.CreateMiningWatcherLinkRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.CreateMiningWatcherLinkResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/watcher-links/create"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.CreateMiningWatcherLinkResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.CreateMiningWatcherLinkResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) ListMiningWatcherLinks(
    ctx context.Context,
    request *gosdk.ListMiningWatcherLinksRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.ListMiningWatcherLinksResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/watcher-links/list"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.ListMiningWatcherLinksResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.ListMiningWatcherLinksResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) CreateMiningAccount(
    ctx context.Context,
    request *gosdk.CreateMiningAccountRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.CreateMiningAccountResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/accounts/create"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.CreateMiningAccountResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.CreateMiningAccountResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

func (r *RawClient) GetMiningAccounts(
    ctx context.Context,
    request *gosdk.GetMiningAccountsRequest,
    opts ...option.RequestOption,
) (*core.Response[*gosdk.GetMiningAccountsResponse], error){
    options := core.NewRequestOptions(opts...)
    baseURL := internal.ResolveBaseURL(
        options.BaseURL,
        internal.ResolveEnvironmentBaseURL(
            options.Environment,
            "Base",
        ),
        r.baseURL,
        internal.ResolveEnvironmentBaseURL(
            r.options.Environment,
            "Base",
        ),
        "https://whitebit.com",
    )
    endpointURL := baseURL + "/api/v4/mining/accounts"
    headers := internal.MergeHeaders(
        r.options.ToHeader(),
        options.ToHeader(),
    )
    headers.Add("Content-Type", "application/json")
    var response *gosdk.GetMiningAccountsResponse
    raw, err := r.caller.Call(
        ctx,
        &internal.CallParams{
            URL: endpointURL,
            Method: http.MethodPost,
            Headers: headers,
            MaxAttempts: options.MaxAttempts,
            BodyProperties: options.BodyProperties,
            QueryParameters: options.QueryParameters,
            Client: options.HTTPClient,
            Request: request,
            Response: &response,
            ErrorDecoder: internal.NewErrorDecoder(gosdk.ErrorCodes),
        },
    )
    if err != nil {
        return nil, err
    }
    return &core.Response[*gosdk.GetMiningAccountsResponse]{
        StatusCode: raw.StatusCode,
        Header: raw.Header,
        Body: response,
    }, nil
}

