// Code generated by Fern. DO NOT EDIT.

package mining_pool_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/whitebit-exchange/go-sdk"
	client "github.com/whitebit-exchange/go-sdk/client"
	option "github.com/whitebit-exchange/go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestMiningPoolGetMiningRewardsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningRewardsRequest{}
	_, invocationErr := client.MiningPool.GetMiningRewards(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningRewardsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningRewardsWithWireMock", "POST", "/api/v4/mining/rewards", nil, 1)
}

func TestMiningPoolGetMiningHashrateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningHashrateRequest{
		Account: "miner123",
	}
	_, invocationErr := client.MiningPool.GetMiningHashrate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningHashrateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningHashrateWithWireMock", "POST", "/api/v4/mining/hashrate", nil, 1)
}

func TestMiningPoolGetMiningPayoutDestinationWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningPayoutDestinationRequest{
		AccountName: "my_miner_01",
	}
	_, invocationErr := client.MiningPool.GetMiningPayoutDestination(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningPayoutDestinationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningPayoutDestinationWithWireMock", "POST", "/api/v4/mining/payout-destination", nil, 1)
}

func TestMiningPoolSetMiningPayoutDestinationWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.SetMiningPayoutDestinationRequest{
		AccountName: "my_miner_01",
		Destination: sdk.SetMiningPayoutDestinationRequestDestinationMainBalance,
	}
	_, invocationErr := client.MiningPool.SetMiningPayoutDestination(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolSetMiningPayoutDestinationWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolSetMiningPayoutDestinationWithWireMock", "POST", "/api/v4/mining/payout-destination/edit", nil, 1)
}

func TestMiningPoolGetMiningMinerInfoWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningMinerInfoRequest{
		Account: "my_miner_01",
	}
	_, invocationErr := client.MiningPool.GetMiningMinerInfo(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningMinerInfoWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningMinerInfoWithWireMock", "POST", "/api/v4/mining/miners/info", nil, 1)
}

func TestMiningPoolGetMiningWorkerNamesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningWorkerNamesRequest{
		Account: "my_miner_01",
	}
	_, invocationErr := client.MiningPool.GetMiningWorkerNames(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningWorkerNamesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningWorkerNamesWithWireMock", "POST", "/api/v4/mining/workers/names", nil, 1)
}

func TestMiningPoolGetMiningWorkerHashrateWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningWorkerHashrateRequest{
		Account: "my_miner_01",
		Worker:  "worker_001",
	}
	_, invocationErr := client.MiningPool.GetMiningWorkerHashrate(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningWorkerHashrateWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningWorkerHashrateWithWireMock", "POST", "/api/v4/mining/workers/hashrate", nil, 1)
}

func TestMiningPoolCreateMiningWatcherLinkWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.CreateMiningWatcherLinkRequest{
		Accounts: []string{
			"my_miner_01",
			"my_miner_02",
		},
		Name: "monitoring_link",
		Permissions: []sdk.CreateMiningWatcherLinkRequestPermissionsItem{
			sdk.CreateMiningWatcherLinkRequestPermissionsItemDashboard,
			sdk.CreateMiningWatcherLinkRequestPermissionsItemWorkers,
		},
		LiveUntil: sdk.CreateMiningWatcherLinkRequestLiveUntilOneH,
	}
	_, invocationErr := client.MiningPool.CreateMiningWatcherLink(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolCreateMiningWatcherLinkWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolCreateMiningWatcherLinkWithWireMock", "POST", "/api/v4/mining/watcher-links/create", nil, 1)
}

func TestMiningPoolListMiningWatcherLinksWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.ListMiningWatcherLinksRequest{
		Account: "my_miner_01",
	}
	_, invocationErr := client.MiningPool.ListMiningWatcherLinks(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolListMiningWatcherLinksWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolListMiningWatcherLinksWithWireMock", "POST", "/api/v4/mining/watcher-links/list", nil, 1)
}

func TestMiningPoolCreateMiningAccountWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.CreateMiningAccountRequest{
		Name:    "my_miner_01",
		Request: "{{request}}",
		Nonce:   1594297865000,
	}
	_, invocationErr := client.MiningPool.CreateMiningAccount(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolCreateMiningAccountWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolCreateMiningAccountWithWireMock", "POST", "/api/v4/mining/accounts/create", nil, 1)
}

func TestMiningPoolGetMiningAccountsWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetMiningAccountsRequest{
		Request: "{{request}}",
		Nonce:   1594297865000,
	}
	_, invocationErr := client.MiningPool.GetMiningAccounts(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestMiningPoolGetMiningAccountsWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestMiningPoolGetMiningAccountsWithWireMock", "POST", "/api/v4/mining/accounts", nil, 1)
}
