// Code generated by Fern. DO NOT EDIT.

package travelrule

import (
	context "context"
	sdk "github.com/whitebit-exchange/go-sdk"
	core "github.com/whitebit-exchange/go-sdk/core"
	internal "github.com/whitebit-exchange/go-sdk/internal"
	option "github.com/whitebit-exchange/go-sdk/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Retrieves the list of Virtual Asset Service Providers (VASPs) that can be used when submitting travel rule data for deposits and withdrawals.
//
// Use the returned `vaspId` when submitting travel rule data if the destination/originating VASP is in this list. If the VASP is not in the list, use `vaspName` as a fallback.
//
// <Accordion title="Errors">
// **API disabled for region (422):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Something went wrong",
//	  "errors": {
//	    "error": ["This endpoint is disabled for your region"]
//	  }
//	}
//
// ```
// </Accordion>
//
// Beyond the errors above, this endpoint can return only the [common authentication errors](/api-reference/authentication).
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
func (c *Client) GetTravelRuleVasps(
	ctx context.Context,
	request *sdk.GetTravelRuleVaspsRequest,
	opts ...option.RequestOption,
) (*sdk.GetTravelRuleVaspsResponse, error) {
	response, err := c.WithRawResponse.GetTravelRuleVasps(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}

// Submits originator information for a deposit that is ready for the travel rule verification.
//
// **Wallet types:**
// - `hosted` - VASP-hosted wallet (exchange, custodian). Requires `vaspData` object.
// - `unhosted` - Self-custody wallet (hardware wallet, software wallet). No VASP required.
//
// **Party types:**
// - `individual` - Natural person. Requires `firstName` and `lastName`.
// - `entity` - Legal entity. Requires `fullName`.
//
// <Accordion title="Errors">
// **Validation failed (400):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Validation failed",
//	  "errors": {
//	    "originator.firstName": ["The first name field is required for individual."],
//	    "originator.address": ["The originator address field is required."]
//	  }
//	}
//
// ```
//
// **Transaction not found (422):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Something went wrong",
//	  "errors": {
//	    "uniqueId": ["Transaction not found"]
//	  }
//	}
//
// ```
//
// **Transaction must be deposit (422):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Something went wrong",
//	  "errors": {
//	    "uniqueId": ["Transaction must be a deposit"]
//	  }
//	}
//
// ```
//
// **Transaction not ready for verification (422):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Something went wrong",
//	  "errors": {
//	    "uniqueId": ["Transaction is not ready for verification"]
//	  }
//	}
//
// ```
//
// **API disabled for region (422):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Something went wrong",
//	  "errors": {
//	    "error": ["This endpoint is disabled for your region"]
//	  }
//	}
//
// ```
//
// **Missing VASP for hosted wallet (400):**
// ```json
//
//	{
//	  "code": 0,
//	  "message": "Validation failed",
//	  "errors": {
//	    "vaspData": ["Either vaspId or vaspName is required for hosted wallets"]
//	  }
//	}
//
// ```
// </Accordion>
//
// Beyond the errors above, this endpoint can return only the [common authentication errors](/api-reference/authentication).
//
// <Warning>
// Rate limit: 1000 requests/10 sec.
// </Warning>
//
// <Note>
// The API does not cache the response.
// </Note>
func (c *Client) SubmitTravelRuleDepositVerification(
	ctx context.Context,
	request *sdk.TravelRuleDepositVerificationRequest,
	opts ...option.RequestOption,
) (*sdk.SubmitTravelRuleDepositVerificationResponse, error) {
	response, err := c.WithRawResponse.SubmitTravelRuleDepositVerification(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
