// Code generated by Fern. DO NOT EDIT.

package public_api_v4_test

import (
	bytes "bytes"
	context "context"
	json "encoding/json"
	require "github.com/stretchr/testify/require"
	http "net/http"
	os "os"
	sdk "github.com/whitebit-exchange/go-sdk"
	client "github.com/whitebit-exchange/go-sdk/client"
	option "github.com/whitebit-exchange/go-sdk/option"
	testing "testing"
)

func VerifyRequestCount(
	t *testing.T,
	testId string,
	method string,
	urlPath string,
	queryParams map[string]string,
	expected int,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WiremockAdminURL := "http://localhost:" + wiremockPort + "/__admin"
	var reqBody bytes.Buffer
	reqBody.WriteString(`{"method":"`)
	reqBody.WriteString(method)
	reqBody.WriteString(`","urlPath":"`)
	reqBody.WriteString(urlPath)
	reqBody.WriteString(`","headers":{"X-Test-Id":{"equalTo":"`)
	reqBody.WriteString(testId)
	reqBody.WriteString(`"}}`)
	if len(queryParams) > 0 {
		reqBody.WriteString(`,"queryParameters":{`)
		first := true
		for key, value := range queryParams {
			if !first {
				reqBody.WriteString(",")
			}
			reqBody.WriteString(`"`)
			reqBody.WriteString(key)
			reqBody.WriteString(`":{"equalTo":"`)
			reqBody.WriteString(value)
			reqBody.WriteString(`"}`)
			first = false
		}
		reqBody.WriteString("}")
	}
	reqBody.WriteString("}")
	resp, err := http.Post(WiremockAdminURL+"/requests/find", "application/json", &reqBody)
	require.NoError(t, err)
	var result struct {
		Requests []interface{} `json:"requests"`
	}
	json.NewDecoder(resp.Body).Decode(&result)
	require.Equal(t, expected, len(result.Requests))
}

func TestPublicAPIV4MaintenanceStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.MaintenanceStatus(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4MaintenanceStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4MaintenanceStatusWithWireMock", "GET", "/api/v4/public/platform/status", nil, 1)
}

func TestPublicAPIV4MarketInfoWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.MarketInfo(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4MarketInfoWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4MarketInfoWithWireMock", "GET", "/api/v4/public/markets", nil, 1)
}

func TestPublicAPIV4MarketActivityWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.MarketActivity(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4MarketActivityWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4MarketActivityWithWireMock", "GET", "/api/v4/public/ticker", nil, 1)
}

func TestPublicAPIV4AssetStatusListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.AssetStatusList(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4AssetStatusListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4AssetStatusListWithWireMock", "GET", "/api/v4/public/assets", nil, 1)
}

func TestPublicAPIV4OrderbookWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetAPIV4PublicOrderbookMarketRequest{
		Market: "BTC_USDT",
		Limit: sdk.Int(
			100,
		),
		Level: sdk.Int(
			2,
		),
	}
	_, invocationErr := client.PublicAPIV4.Orderbook(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4OrderbookWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4OrderbookWithWireMock", "GET", "/api/v4/public/orderbook/BTC_USDT", map[string]string{"limit": "100", "level": "2"}, 1)
}

func TestPublicAPIV4DepthWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetAPIV4PublicOrderbookDepthMarketRequest{
		Market: "BTC_USDT",
	}
	_, invocationErr := client.PublicAPIV4.Depth(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4DepthWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4DepthWithWireMock", "GET", "/api/v4/public/orderbook/depth/BTC_USDT", nil, 1)
}

func TestPublicAPIV4RecentTradesWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetAPIV4PublicTradesMarketRequest{
		Market: "BTC_USDT",
	}
	_, invocationErr := client.PublicAPIV4.RecentTrades(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4RecentTradesWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4RecentTradesWithWireMock", "GET", "/api/v4/public/trades/BTC_USDT", nil, 1)
}

func TestPublicAPIV4FeeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.Fee(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4FeeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4FeeWithWireMock", "GET", "/api/v4/public/fee", nil, 1)
}

func TestPublicAPIV4ServerTimeWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.ServerTime(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4ServerTimeWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4ServerTimeWithWireMock", "GET", "/api/v4/public/time", nil, 1)
}

func TestPublicAPIV4ServerStatusWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.ServerStatus(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4ServerStatusWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4ServerStatusWithWireMock", "GET", "/api/v4/public/ping", nil, 1)
}

func TestPublicAPIV4CollateralMarketsListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.CollateralMarketsList(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4CollateralMarketsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4CollateralMarketsListWithWireMock", "GET", "/api/v4/public/collateral/markets", nil, 1)
}

func TestPublicAPIV4AvailableFuturesMarketsListWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.AvailableFuturesMarketsList(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4AvailableFuturesMarketsListWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4AvailableFuturesMarketsListWithWireMock", "GET", "/api/v4/public/futures", nil, 1)
}

func TestPublicAPIV4FundingHistoryWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	request := &sdk.GetAPIV4PublicFundingHistoryMarketRequest{
		Market: "BTC_PERP",
		StartDate: sdk.Int(
			1752480000,
		),
		EndDate: sdk.Int(
			1752537600,
		),
		Limit: sdk.Int(
			100,
		),
		Offset: sdk.Int(
			0,
		),
	}
	_, invocationErr := client.PublicAPIV4.FundingHistory(
		context.TODO(),
		request,
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4FundingHistoryWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4FundingHistoryWithWireMock", "GET", "/api/v4/public/funding-history/BTC_PERP", map[string]string{"startDate": "1752480000", "endDate": "1752537600", "limit": "100", "offset": "0"}, 1)
}

func TestPublicAPIV4MiningPoolOverviewWithWireMock(
	t *testing.T,
) {
	wiremockPort := os.Getenv("WIREMOCK_PORT")
	if wiremockPort == "" {
		wiremockPort = "8080"
	}
	WireMockBaseURL := "http://localhost:" + wiremockPort
	client := client.NewClient(
		option.WithBaseURL(WireMockBaseURL),
	)
	_, invocationErr := client.PublicAPIV4.MiningPoolOverview(
		context.TODO(),
		option.WithHTTPHeader(
			http.Header{"X-Test-Id": []string{"TestPublicAPIV4MiningPoolOverviewWithWireMock"}},
		),
	)

	require.NoError(t, invocationErr, "Client method call should succeed")
	VerifyRequestCount(t, "TestPublicAPIV4MiningPoolOverviewWithWireMock", "GET", "/api/v4/public/mining-pool", nil, 1)
}
